mthom/scryer-prolog

- src/prolog/lib/error.pl
Example:
?- can_be(list, [a,b|Ls]).
%@ true.
> correct can_be/2 for partial lists

- src/prolog/lib/error.pl
Strictly speaking, type is currently not a type, so a domain error is
appropriate if Type is not a valid type. However, there are also other
cases where new types have been introduced in the past, and this
seems a good candidate for a new type. Let us hence use a type error.
Example:
?- can_be(listi, [a,b|Ls]).
%@ ERROR: Type error: `type' expected, found `listi' (an atom)
> ENHANCED: Better error handling if Type is invalid.

- Cargo.toml
It wasn't able to compile with latest Rust 1.33:
```
error[E0034]: multiple applicable items in scope
--> /home/akochkov/.cargo/registry/src/github.com-1ecc6299db9ec823/downcast-0.9.2/src/lib.rs:120:38
|
120 |     fn is_type(&self) -> bool { self.type_id() == TypeId::of::<T>() }
|                                      ^^^^^^^ multiple `type_id` found
|
note: candidate #1 is defined in the trait `Any`
--> /home/akochkov/.cargo/registry/src/github.com-1ecc6299db9ec823/downcast-0.9.2/src/lib.rs:29:5
|
29  |     fn type_id(&self) -> TypeId { TypeId::of::<Self>() }
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
= help: to disambiguate the method call, write `Any::type_id(&self)` instead
note: candidate #2 is defined in the trait `std::any::Any`
= help: to disambiguate the method call, write …
```
> Update downcast dependency

- src/prolog/lib/si.pl
These are safe type tests, please consider including this library in Scryer Prolog. It would make Scryer the first system to support these new predicates.
This is how type tests should have been defined in the first place. Notably, exceptions are thrown if no decision can be made at this point.
Possibly other sound predicates are also good candidates for inclusion in this new library in the future. Hence the name "si", which can also be read as "safe inference" or "sound inference".
> ADDED: library(si) for safe type tests.

- src/prolog/heap_print.rs
- src/prolog/iterators.rs
- src/prolog/machine/machine_errors.rs
- src/prolog/machine/machine_state.rs
- src/prolog/machine/machine_state_impl.rs
- src/prolog/machine/mod.rs
- src/prolog/machine/system_calls.rs
- src/prolog/read.rs
Hi there,
Thanks for the solid project! I'm enjoying using it! 
Just want to provide some little fixes which triggers warning on latest toolchains :-) We use `cargo fix` on nightly-2019-10-04 toolchain to generate the patch automatically:
- Fixed `...` to `..=`
- Fixed trait object to `dyn` trait object
Hope you like it!
Best,
Yu
> Fix some old Rust codes

- src/prolog/lib/clpb.pl
library(clpb) provides CLP(B), Constraint Logic Programming over
Boolean variables. It is a SAT solver that seamlessly integrates into
Prolog in the sense that logic variables are used to state constraints
and report solutions. This library can be used to model and solve many
combinatorial problems such as verification, allocation and covering
tasks.
CLP(B) is an instance of the general CLP(X) scheme, extending logic
programming with reasoning over specialised domains.
The implementation is based on reduced and ordered Binary Decision
Diagrams (BDDs).
Usage examples of this library are available in a public git
repository:
https://github.com/triska/clpb
For more information, benchmarks and publications visit:
https://www.metalevel.at/clpb/
The interface of this library is consciously kept …
> ADDED: CLP(B), Constraint Logic Programming over Boolean Variables

- src/prolog/lib/clpb.pl
- src/prolog/lib/error.pl
This adds support for weighted_maximum/3. 
random_labeling/2 is the only remaining CLP(B) predicate that needs further support from built-ins. Notably, set_random/1 and maybe/0 must be provided by the engine to set a random seed and succeed with probability 0.5, respectively.
> weighted_maximum/3 now works

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/prolog/machine/system_calls.rs
- src/prolog/mod.rs
This will depends on https://github.com/mthom/prolog_parser/pull/1
I've create this PR to try to increase the awareness of the issues raised in https://github.com/mthom/prolog_parser/pull/1.
Basically this implements part of the rug interface using num crate, making it easy for cross compiling and distributing static binaries.
> Add feature num to use num crate in place of rug.

- src/prolog/machine/system_calls.rs
I don't know if it's in ISO Prolog or not, but in SWI Prolog, pressing 'n' does the same as ';'. I was very used to that behavior, so I added it but I don't know if it's standard or worth adding it.
> add n as an option to get the next solution

- src/prolog/lib/format.pl
This library provides the nonterminal **`format_//2`** to describe formatted&nbsp;strings. In addition, `format/2` is provided for impure output.
Please see the commit message for more information.
This pull request requires #280, #283 and #281 to to be resolved.
> ADDED: library(format), describing strings with format_//2

- src/prolog/machine/system_calls.rs
- src/prolog/toplevel.pl
These two commits introduce "p" and "h" to print terms *with* depth limit, and to display a help message during toplevel interaction.
> Two small toplevel features

- README.md
This commit adds a brief overview and pointers to library modules that ship with Scryer Prolog.
I hope this is useful. Please adapt it at will if necessary.
> include a short overview of notable libraries

- Cargo.lock
- Cargo.toml
- src/main.rs
Added a new dependency to take care of pulling in the version from git
at build time.
Args handling is minimalistic, but there wasn't any before, so I figured
this might do for now. (Eventually, some proper `--help` and usage
output might come in handy?)
Meant to fix #303.
> main: add -v/--version flag

- README.md
- src/prolog/lib/clpz.pl
library(clpz) implements declarative integer arithmetic.
The most important predicates for reasoning about integers are:
(#=)/2    equality
(#\=)/2   disequality
(#<)/2    less than
(#>)/2    greater than
(#=<)/2   less than or equal to
(#>=)/2   greater than or equal to
In addition, the library provides several global constraints, such as
all_distinct/1 and global_cardinality/2, and reification predicates
that reflect the truth values of constraints into integer variables.
Enumeration predicates such label/1 and labeling/2 can be used to
search for solutions over finite domains.
Almost all Prolog programs also reason about integers. Therefore, I
recommend to add this library to your .scryerrc configuration file so
that declarative integer arithmetic is available in all your programs. …
> ADDED: CLP(ℤ), Constraint Logic Programming over Integers

- src/prolog/lib/clpz.pl
These two commits implement a small name change to enable the monotonic execution mode (providing `clpz:monotonic` in analogy to `clpb:monotonic/0`), and also make the extensional relation constraint `tuples_in/2` work.
> clpz_monotonic/0 --> monotonic/0

- README.md
Also, explain in more detail what this feature means to Prolog
application programmers, and the strategic direction of Scryer.
This is a really great feature, well worth advertising and explaining.
> extend description of strings and partial strings

- src/prolog/examples/bimetatrans_ruleml.pl
Here are a few changes to one of the example programs. Please review, and merge if applicable.
The brilliance of Scryer's efficient string implementation is that they can be treated as completely normal lists in Prolog code. It should never be necessary to refer explicitly to their internal implementation name ("partial&nbsp;strings").
As far as Prolog code is concerned, strings are simply lists, and thus amenable to elegant processing with&nbsp;DCGs.
> Bimeta example

- README.md
As of 6e4b76a3b40beb02556bd8847fe96789fa0ef012, the use of
`partial_string/3` can be replaced by `(=)/2` in this example.
Please review, and merge if applicable
> incorporate the latest improvements in the description of partial strings

- src/prolog/lib/format.pl
As a brief followup, I think including a newline makes `portrtay_clause/1` even more useful.
Sample program where I am now using this feature:
https://www.metalevel.at/logic/plres.pl
This implements the resolution calculus for propositional logic, and emits the result for easy verification with Prolog.
> also include a newline in portray_clause/1

- src/prolog/machine/mod.rs
- src/prolog/toplevel.pl
In run_top_level: rename variables, make them partial strings
The rename is mostly cosmetic: all of argv is passed, and if argv
contains flags, goals, etc, it's more than filenames.
Using partial strings instead of atom came from discussions about how to
pass goals in the CLI, and can thus be considered preliminary work for
that.
In toplevel.pl: convert partial string to atom before passing it to
`use_module`.
-----
ℹ️New PR for clarity. This is a baby step towards #187, as came up in the discussion of my previous attempt in #313. Here, we only change the format of argv passed into toplevel. Further steps, like processing `-v/--version`, and ultimately taking in goals, can happen in follow-up work.
~⚠️ The change doesn't *work*, it seems that `atom_chars(Mod, Mod0)` fails to convert the …
> use partial strings for passing argv to toplevel.pl

- src/prolog/lib/pairs.pl
Pairs must be keysorted and may also contain variables as keys.
Examples:
?-  group_pairs_by_key([1-a,1-b,2-c], Ps).
Ps = [1-[a,b],2-[c]].
?-  group_pairs_by_key([X-a,X-b,2-c], Ps).
Ps = [X-[a,b],2-[c]].
> ADDED: group_pairs_by_key/2

- src/prolog/lib/lists.pl
Example:
?- list_to_set([B,a,b,a,B,A,b,A], Ls).
Ls = [B,a,b,A]
;  false.
> ADDED: list_to_set/2, using the first occurrence of each element

- src/prolog/lib/format.pl
- src/prolog/toplevel.pl
This is to accommodate goals that are used for their side-effects,
when we are interested in their output.
Examples:
?- portray_clause((a :- a)).
a :-
a.
true
;  false.
?- format("hello~w~n", [!]).
hello!
true
;  false.
> Delay toplevel output until after the goal succeeds

- Cargo.lock
- Cargo.toml
- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/time.pl
- src/prolog/machine/system_calls.rs
`sleep/1` and predicates for reasoning about time stamps should also be added to this library.
> ADDED: library(time), providing time/1 for benchmarking

- src/prolog/lib/time.pl
`setup_call_cleanup/3` is very useful for this.
It seems slightly preferable to write this as `setup_call_cleanup('$cpu_now'(T0), ...`, but that unfortunately does not work.
> ENHANCED: time(Goal) now also reports the time if Goal fails

- src/prolog/lib/format.pl
Example:
:- dynamic(a/1).
a(X) :- X = true, b(X).
Yielding:
?- listing(a/1).
%@ a(A) :-
%@    A=true,
%@    b(A).
%@    true.
listing/1 only works for predicates and DCGs that are declared dynamic/1.
> ADDED: library(format) now provides a rudimentary version of listing/1

- README.md
- src/prolog/lib/charsio.pl
For example, `char_type/2` now throws domain errors if an unknown type is specified. This helps when porting programs to Scryer Prolog, and is also a good guard against typos, because an exception lets programmers quickly pinpoint the root cause of issues.
> Several smaller improvements

- README.md
These two commits document tabling and `library(cont)` in the README.
> Two small documentation additions

- README.md
- src/prolog/lib/arithmetic.pl
- src/prolog/lib/clpb.pl
- src/prolog/lib/clpz.pl
- src/prolog/lib/error.pl
- src/prolog/lib/format.pl
- src/prolog/lib/pio.pl
- src/prolog/lib/random.pl
- src/prolog/lib/time.pl
With these commits, `library(error)` now exports the new predicates `instantiation_error/1`, `domain_error/3` and `type_error/3`.
Other libraries now use these predicates to simplify the code and make it less error-prone.
Also, include the new `library(random)` in the overview and add a usage comment at the start of the file.
> Introduce and use new predicates for throwing ISO errors

- README.md
- src/prolog/lib/charsio.pl
- src/prolog/lib/clpz.pl
- src/prolog/lib/lists.pl
- src/prolog/lib/random.pl
- src/prolog/lib/time.pl
In addition to a few small corrections and improvements, these commits also provide `nth0/3` in `library(lists)`.
Using `nth0/3` is often a sign that better data structures could be appropriate. On the other hand, it is sometimes useful to have it.
> Small corrections, additions and improvements

- src/prolog/lib/clpz.pl
Example:
?- freeze(B, queen_value_truth(C,N,B)), Q #= N #<==> B.
clpz:(Q#=N#<==>B), clpz:(B in 0..1), freeze:freeze(B,queen_value_truth(C,N,B))
;  false.
> correct verify_attributes/3 for variables that have no CLP(ℤ) attribute attached (#373)

- src/prolog/lib/clpz.pl
Example:
integer_successor(I0, I) :- I #= I0 + 1.
Yielding:
?- listing(integer_successor/2).
integer_successor(A,B) :-
(  integer(B) ->
(  integer(A) ->
B=:=A+1
;  C is B,
clpz:clpz_equal(C,A+1)
)
;  (  integer(A) ->
(  var(B) ->
B is A+1
;  C is A+1,
clpz:clpz_equal(B,C)
)
;  clpz:clpz_equal(B,A+1)
)
).
Thus, fast low-level arithmetic is used whenever possible.
> enable goal expansion for CLP(ℤ) goals

- src/prolog/lib/clpz.pl
For instance, consider:
t(X) :- X #= 1.
We *cannot* expand this to:
?- listing(t/1).
t(A) :-
(  integer(A) ->
A=:=A
;  (  var(A) ->
true
;  true,
clpz:clpz_equal(A,A)
)
).
Also, a new binding *must not* be dragged outside of disjunctions,
since the code may look for example like this:
i(X) :-
(   X #= 3
;   X #= 4
).
This commit fixes such issues, and still rewrites CLP(ℤ) expressions
as far as possible already at compilation time.
For example:
n(X) :- X #= 1+3.
This is now compiled to (note that 1+3 is evaluated to 4):
?- listing(n/1).
n(A) :-
(  integer(A) ->
A=:=4
;  (  var(A) ->
A=4
;  B=4,
clpz:clpz_equal(A,B)
)
).
Ideally, it should be compiled to:
n(4).
> correct overeager CLP(ℤ) goal expansion

- Cargo.toml
- src/prolog/clause_types.rs
- src/prolog/lib/crypto.pl
- src/prolog/machine/system_calls.rs
The ring crate is used since it will be needed also for future predicates in library(crypto).
This is the first step to porting [Bitcoinolog](https://www.metalevel.at/bitcoinolog/) to Scryer Prolog.
> ADDED: crypto_n_random_bytes/2, creating cryptographically secure random bytes

- README.md
- src/prolog/lib/crypto.pl
This is useful to establish shared secrets, using ECDH key exchange.
Note that CLP(ℤ) goal expansion is currently disabled due to #445,
and this slows down the computations considerably for the time being.
We can trust the results only when #499 is resolved.
> ADDED: Reasoning about elliptic curves in library(crypto).

- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/crypto.pl
- src/prolog/machine/machine_state_impl.rs
- src/prolog/machine/system_calls.rs
This is useful to generate keys and initialization vectors from suitable input keying material, so that future predicates for symmetric encryption can be used with appropriate parameters.
> ADDED: HMAC-based key derivation (HKDF) via crypto_data_hkdf/4

- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/crypto.pl
- src/prolog/machine/system_calls.rs
The new predicates crypto_password_hash/[2,3] let you store passwords safely, and easily verify passwords later.
Also, many thanks to @matt2xu: I am now already using the new predicate `chars_utf8bytes/2` to use the UTF-8 representation of characters for hashing.
> ADDED: Password-based key derivation (PBKDF2)

- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/crypto.pl
- src/prolog/lib/format.pl
- src/prolog/machine/system_calls.rs
This PR implements **authenticated symmetric encryption** via `crypto_data_encrypt/6` and `crypto_data_decrypt/4` for encryption and decryption using the fast and secure ChaCha20 stream cipher in tandem with the Poly1305 authenticator.
Here is an example query to try:
<pre>
?- Algorithm = 'chacha20-poly1305',
crypto_n_random_bytes(32, Key),
crypto_n_random_bytes(12, IV),
crypto_data_encrypt("this text is to be encrypted", Algorithm,
Key, IV, CipherText, [tag(Tag)]),
crypto_data_decrypt(CipherText, Algorithm,
Key, IV, RecoveredText, [tag(Tag)]).
</pre>
It also adds the new `encoding/1` option to `crypto_data_hash/3` and `crypto_data_hkdf/4`. By specifying `encoding(octet)` as option, a list of characters can be treated as raw bytes. The default encoding is `utf8`.
Scryer Prolog's efficient …
> Authenticated encryption in library(crypto), new encoding/1 option for hashes

- .dockerignore
- Dockerfile
- README.md
Deploying scryer-prolog to Docker will allow it to reach a farther audience and open up the possibility of building Docker applications based on it.
It also opens it up to Windows folks (I run it just fine through [Docker Desktop for Windows](https://hub.docker.com/editions/community/docker-ce-desktop-windows)).
I played around with the Dockerfile until I got the image down to 77MB, which is not bad.
If deploying to Docker seems like a good idea, let's discuss the best way to do it. I don't want you to have to spend hours deploying crates, docker images, etc. Maybe setting up Travis CI is a good idea? It's free for open source projects.
Let me know what you think!
> Created and Tested Dockerfile

- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/format.pl
- src/prolog/machine/system_calls.rs
In addition, 48c0b0ab3c9eb4f8c8ec9b953d0c6cc61a0a47fc introduces and uses a specialised internal predicate that considerably speeds&nbsp;up formatted output to binary&nbsp;streams. This is useful for example in web&nbsp;servers.
Please review, and merge if applicable. Thank you a lot!
> ADDED: format/3, writing formatted output to a stream

- .dockerignore
- Dockerfile
- README.md
I reran `docker build -t scryer-prolog .` on my Windows laptop and it works just fine!
Now that I think about it, I'm actually surprised that it works because only the compiled scryer-prolog executable is copied to the destination container, without any other files. That must mean that all the Prolog libraries that ship with Scryer Prolog are baked into the executable? I can certainly use them just fine from within Docker, so that must be the case.
The next step is to add the Docker build step to the Travis CI release process somehow, but it's not urgent.
> Valid Dockerfile and README

- src/prolog/lib/format.pl
Notably, arithmetic expressions are now evaluated for `~d`, `~D`, `~f`, `~r` and `~R`.
Example:
<pre>
<b>?- phrase(format_("~d", [1+2]), Cs).</b>
Cs = "3"
;  false.
</pre>
> Various improvements for format_//2

- Cargo.toml
- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/error.pl
- src/prolog/lib/sockets.pl
- src/prolog/machine/streams.rs
- src/prolog/machine/system_calls.rs
Use `tls(true)` to negotiate an encrypted network connection via TLS.
This addresses #503.
The changes for supporting TLS seem quite small to me: If a better way to establish TLS client connections is implemented later, it will be easy to remove or adapt them. For now, I think it is good to be able to easily establish encrypted connections.
Example:
<pre>
<b>?- socket_client_open('metalevel.at':443, S, [tls(true)]),
format(S, "GET / HTTP/1.1\r\nHost: www.metalevel.at\r\n\r\n", []),
repeat,
get_char(S, Char),
write(Char),
sleep(0.01),
false.</b>
HTTP/1.1 200 OK
Date: Sun, 07 Jun 2020 21:18:22 GMT
Connection: Keep-Alive
Strict-Transport-Security: max-age=63072000; includeSubdomains
etc.
</pre>
> ADDED: Encrypted client connections in library(sockets) via new option tls/1.

- src/prolog/machine/system_calls.rs
Example:
?- socket_client_open('expired.badssl.com':443, S, [tls(true)]).
caught: error(permission_error(open,source_sink,'expired.badssl.com'),socket_client_open/3)
> ENHANCED: throw Prolog exception on expired certificates

- Cargo.toml
- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/time.pl
- src/prolog/machine/system_calls.rs
`current_time/1` yields the current system time as an opaque time stamp.
> ADDED: format_time//2 for describing strings involving dates and times

- README.md
- src/prolog/clause_types.rs
- src/prolog/lib/pio.pl
- src/prolog/machine/system_calls.rs
This allows processing extremely large files. In addition, the efficient string representation helps to reduce memory usage.
These features unleash the full power of Prolog for text processing, the exact use case Prolog was designed for.
This depends on #586 being corrected. Please review, and merge if applicable. Many thanks!
> ENHANCED: phrase_from_file/[2,3] now read the file lazily. 

- src/clause_types.rs
- src/lib/pio.pl
- src/machine/system_calls.rs
> ENHANCED: Read more characters at once, significantly speeding up library(pio)

- src/lib/format.pl
- src/machine/system_calls.rs
This is also more secure, since it does not change the atom table and therefore leaves little trace of what was processed.
> ENHANCED: faster format/3 when writing to binary streams

- src/lib/charsio.pl
It yields a list difference, retaining the newline character.
This works for both binary and text streams.
> ADDED: read_line_to_chars/3, reading up to and including "\n" from a stream

- src/clause_types.rs
- src/lib/format.pl
- src/machine/system_calls.rs
This is now also used by `format/2` to emit output on the terminal, and significantly speeds up toplevel output of long strings.
Please review, and merge if applicable. Thank you a lot!
> ENHANCED: much faster format/3 for text streams

- src/machine/system_calls.rs
Example:
?- put_char(hello).
%@ caught: error(type_error(character,hello),put_char/2)
Please review, and merge if applicable. Thank you a lot!
> put_char/[1,2]: throw type errors for atoms that are not characters

- README.md
- src/lib/http/http_open.pl
Currently, only UTF-8 encoding is supported.
Example:
<pre>
?- http_open("https://github.com/mthom/scryer-prolog", Stream, []),
repeat,
get_char(Stream, C),
write(C),
sleep(0.01),
false.
</pre>
Yielding:
<pre>
%@ 
%@ 
%@ 
%@ 
%@ 
%@ &lt;!DOCTYPE html&gt;
%@ &lt;html lang="en"&gt;
%@   &lt;head&gt;
%@     &lt;meta charset="utf-8"&gt;
</pre>
Please also note that the library cannot yet be loaded via `use_module/1`, because directories are not supported:
<pre>
<b>?- use_module(library(http/http_open)).</b>
%@ thread 'main' panicked at 'internal error: entered unreachable code', src/machine/mod.rs:685:21
%@ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</pre>
Please review, and merge once  this is resolved. Thank you a lot!
To conveniently analyze web pages …
> ADDED: library(http/http_open), opening HTTP and HTTPS streams for reading

- Cargo.toml
- README.md
- src/clause_types.rs
- src/lib/sgml.pl
- src/machine/system_calls.rs
We are now getting close to convenient reasoning about HTML files.
This library can be nicely used in tandem with `http_open/3` (see #592 ) to read an HTML file from a stream.
Please review, and merge if applicable. Thank you a lot!
> ADDED: library(sgml), providing load_html/3 to parse HTML documents

- src/lib/format.pl
Without this, we do not get a (timely) prompt in cases like:
?- format("press a key: ", []), get_single_char(C).
whereas for example write/1 already works in such cases:
?- write('press a key: '), get_single_char(C).
press a key:
> ENHANCED: flush output for impure I/O (format/[2,3], portray_clause/1 etc.)

- src/lib/crypto.pl
- src/machine/system_calls.rs
This uses a newly available function to shorten the implementation of several cryptographic routines, and also applies deref(...) to integer arguments.
> Shorten and improve implementation of several cryptographic routines

- src/lib/clpb.pl
Examples:
?- taut(X=:=X,1).
clpb:sat(X=:=X)
;  false.
?- taut(X=\=X,0).
clpb:sat(X=:=X)
;  false.
> omit internal attributes in residual goals when using taut/2

- src/machine/system_calls.rs
Example:
?- load_xml("<schemaRef type=\"simple\"/>", Node, []).
Node = [element(schemaRef,[type="simple"],[])].
This is necessary for example to parse XBRL files. See #665.
> library(sgml): Correctly parse XML leaf nodes that are not text nodes.

- src/lib/clpb.pl
This is necessary to actually take the new value into account.
Example:
?- sat(A*B>=C*D), A=1,B=0,C=1,D=1.
false.
This addresses #670.
> FIXED: CLP(B): Delay BDD restriction until after the instantiation.

- README.md
- src/lib/iso_ext.pl
A thread-safe implementation is possible for example with
'$nb_setarg'/3 (see #390)<s>, and termination properties will be improved
once #685 is resolved</s> [<b>done!</b>].
The idea of this predicate is to relate a goal to its N-th answer.
> ADDED: Preliminary version of call_nth/2.

- src/machine/system_calls.rs
This addresses #693.
Many thanks to @notoria for a brilliant test case, and the
suggestion of this correction!
> FIXED: reliably write all characters when using format/3

- src/lib/files.pl
We now throw exceptions instead of failing silently, or even crashing
when using file_size/2 etc. with nonexistent files.
> ENHANCED: library(files): Error handling if requested files do not exist.

- src/lib/clpz.pl
These predicates are intended for constructs from `library(reif)`, such
as `if_/3`. For the time being, they are defined here. If you have any
recommendations or comments regarding the best location of these
predicates, or need more of them, please file an issue.
Suggested by @Qqwy in https://github.com/triska/clpz/issues/12.
Many thanks!
> ADDED: Provisional support for (#=)/3 and (#<)/3.

- src/lib/lists.pl
I was doing Advent of Code in Prolog and while SWI and Tau define max_list and min_list, I found with a surprise that Scryer doesn't. They're very easy to implement by oneself and I don't know if it is the most efficient way, but I think it is useful to have them in the standard library.
> Add list_max & list_min to lists module

- Cargo.lock
- Cargo.toml
- src/read.rs
I've added history file support to the REPL using RustyLine (which I upgraded to 7.0 because append_history was not available in 6.0). Closes #152 
The history files in $HOME/.scryer_history, next to .scryerrc. Lines are saved as they're added to the in-memory history. It is not the most efficient way I think, but saving on closing turned up to be a bit more difficult. Also with this solution, input errors don't destroy the REPL history (right now if you insert a bad input, you lose your in-memory history, because readline gets re-created).
> History file support (Rustyline 7.0) (#152)

- src/lib/format.pl
This works as soon as #732 is merged, since then maplist/N and foldl/N
are deterministic in the required cases.
This also resolves the extra choicepoint of time/1 (see #378).
Many thanks to @notoria for implementing better indexing in #732,
which allowed me to find this opportunity for improvement!
> ENHANCED: format_//2, format/[2,3], portray_clause/1 are now deterministic

- README.md
- src/lib/http/http_server.pl
First version of the pure Prolog HTTP server
Sample app:
```
:- use_module(library(http/http_server)).
:- use_module(library(lists)).
:- use_module(library(dcgs)).
:- use_module(library(format)).
text_handler(Request, Response) :-
http_status_code(Response, 200),
http_body(Response, text("Welcome to Scryer Prolog!")).
sample_handler(Request, Response) :-
http_headers(Request, Headers),
member("user-agent"-UserAgent, Headers),
http_body(Response, text(UserAgent)).
sample_body_handler(Request, Response) :-
http_body(Request, binary(Body)),
http_body(Response, binary(Body)),
http_headers(Response, ["content-type"-"application/json"]).
text_echo_handler(Request, Response) :-
http_body(Request, text(TextBody)),
http_body(Response, text(TextBody)).
parameter_handler(User, Request, Response) :- …
```
> HTTP Server

- .github/workflows/test.yml
- src/lib/http/http_server.pl
Adds support for application/x-www-form-urlencoded forms (the default in HTML if there are no files) and tries to address some syntax issues discussed here: https://github.com/mthom/scryer-prolog/issues/763
Tests have been updated: https://github.com/aarroyoc/scryer-http-test/commit/45c86f2621c343e90f20338ddc75b19d17d11940
> HTTP Server: urlencoded forms and some syntax improvements

- src/lib/clpz.pl
This is needed for all_distinct/1 etc.
Example:
?- all_distinct([X,Y,Z]).
clpz:all_distinct([X,Y,Z])
;  false.
> add meta_predicate declaration for with_local_attributes/3

- src/lib/format.pl
Therefore, subsequent uses of ~N| now yield the specified column,
instead of potentially overshooting.
Example:
?- format("hello~|~t~8|!", []).
hello   !   true.
Such cases are probably rather uncommon: Relative positioning with ~N+
is more likely to be used in such cases, and that worked as intended
also previously as it does now:
?- format("hello~|~t~3+!", []).
hello   !   true.
In fact, if absolute positions are used, then ~| can be omitted entirely:
?- format("hello~t~8|!", []).
hello   !   true.
> ~| now incorporates the number of characters described so far

- README.md
- src/lib/uuid.pl
I don't know if it's useful enough to be included, but here's a UUIDv4 native Prolog library.
```
?- uuidv4(X).
X = [42,147,248,242,117,196,79,2,129,159|...].
?- uuidv4_string(X).
X = "428499fc-76e3-4240- ...".
?- uuidv4(X), uuid_string(X, S).
X = [173,12,244,152,139,118,64,139,137,4|...], S = "ad0cf498-8b76-408b- ...".
?- uuid_string(X, "61ae692e-eaf6-4199-8dd3-9f01db70a20b").
X = [97,174,105,46,234,246,65,153,141,211|...].
```
> UUIDv4 library

- src/lib/http/http_server.pl
I was just updating the HTTP server code to not be a breaking change by using @notoria idea (https://github.com/mthom/scryer-prolog/issues/824#issuecomment-782596516) but I couldn't be fast enough to implement it before the opened PR got merged. Please consider this the real fix to the HTTP server.
> Fix HTTP server in rebis 

- src/lib/clpb.pl
- src/lib/format.pl
This addresses https://github.com/triska/clpz/issues/15.
Many thanks to @jburse!
> CLP(B) correction

- src/arithmetic.rs
- src/machine/arithmetic_ops.rs
This constant is used e.g. in Logtalk `lgtunit` tool for approximate float comparison when defining tests. It's also a de facto standard constant implemented by e.g. B-Prolog, CxProlog, GNU Prolog, LVM, SWI-Prolog, YAP, XSB, Tau Prolog, and Trealla Prolog.
> Add epsilon/0 arithmetic constant

- src/lib/lists.pl
> Ported permutation/2 from SWI library(lists)

- src/lib/builtins.pl
With this pull request, a goal such as `char_code(a,x)` will throw the expected `type_error(integer,x)` error instead of failing. With this fix, all `logtalk3/tests/prolog/predicates/char_code_2` tests pass.
> Fix char_code/2 predicate failure instead of exception on non-integer second argument

- src/lib/builtins.pl
As per standard. With this pull requests, all Logtalk's compliance tests for this control construct pass.
> Fix throw/1 control construct to throw an instantiation error when the argument is not bound

- src/lib/builtins.pl
This pull requests fixes the `retractall/1` predicate to retract both facts and rules. All Logtalk compliance tests now pass.
This pull request also fixes some of the bugs with `retract/1` when retracting rules. But there are still seven compliance bugs that need fixing (run the Logtalk compliance tests for the predicate for details).
> Fixes for retract predicates

- src/lib/clpz.pl
This is to preserve domain errors instead of failing silently. Example:
?- 5 #> 3 #<==> 2.
%@ caught: error(domain_error(clpz_reifiable_expression,2),unknown(2)-1)
> check for correct domain of integers in reifiable expressions also in the expanded code

- src/clause_types.rs
- src/lib/arithmetic.pl
- src/machine/system_calls.rs
These changes resolve #981 , and introduce a new built-in function `popcount/1` which determines how many positive bits comprise any given integer value.
> Add popcount/2

- src/lib/dcgs.pl
I propose to add **`... //0`** to `library(dcgs)` so that it is more readily available.
This is a very versatile nonterminal. For instance, repeated elements in a list can be described like this:
<pre>
<b>?- phrase((...,[E],...,[E],...), "hello!!").</b>
%@    E = l
%@ ;  E = !
%@ ;  false.
</pre>
Many beginners will benefit from this nonterminal, especially when defining predicates that involve lists. For instance, the last element of a list can be described like this:
<pre>
<b>?- phrase((...,[L]), "abc").</b>
%@    L = c
%@ ;  false.
</pre>
Are there any opinions on this? Feedback is highly welcome!
> ADDED: ... //0, describing an arbitrary number of elements

- src/lib/format.pl
This is for compatibility with Quintus, SICStus and GNU Prolog,
addressing #1024.
Example:
?- format("~r", [10]).
%@ 12   true.
> ENHANCED: If N is omitted in ~Nr or ~NR, it defaults to 8.

- src/lib/format.pl
This addresses #1024.
Example:
?- format("hello ~0r!", [12]).
%@ caught: error(domain_error(format_string,"~0r"),format_//2)
> ENHANCED: format_string domain error for invalid radix in format string

- src/lib/format.pl
Example:
?- format("~d", []).
%@ caught: error(domain_error(non_empty_list,[]),format_//2)
> ENHANCED: Domain error non_empty_list for empty arguments, addressing #1024

- crates/num-rug-adapter/src/lib.rs
Solves https://github.com/mthom/scryer-prolog/issues/1009 and allows compiling again with the num feature
> Fix #1009 by providing a naive num-bigint implementation of count_ones

- src/lib/pio.pl
This proposal is to add a rudimentary version of `phrase_to_file/2` so that Prolog programmers can already try this idea and use it in practice, in analogy to what we previously had with `phrase_from_file/2` before it was replaced by the current version which actually reads lazily.
Please see #691 for more information about the eventual version.
If you have any thoughts about this, please comment. Thank you a lot!
> ADDED: Rudimentary version of phrase_to_file/2 in library(pio)

- src/loader.pl
Sample calls:
```text
$ scryer-prolog
?- use_module(library(lists)).
true.
?- current_module(lists).
true.
?- current_module(foobar).
false.
```
The current definition of the `'$module_exists'/1` internal predicate should eventually be updated to allow enumerating loaded modules by backtracking. When that is done, the definition of the `current_module/1` predicate in this pull request should be updated to:
```logtalk
current_module(Module) :-
(  nonvar(Module), \+ atom(Module) ->
type_error(atom, Module, current_module/1)
;  '$module_exists'(Module)
).
```
Still, this pull request allows using Logtalk's `lgtunit` to test module code without requiring turning off important linter warnings as discussed in #896.
> Add preliminary current_module/1 predicate definition requiring a bound argument

- src/clause_types.rs
- src/lib/charsio.pl
- src/lib/crypto.pl
- src/lib/format.pl
- src/machine/system_calls.rs
This pull request uses `partial_string/1` and the new internal predicate `'$first_non_octet/2'` to significantly improve the performance of domain checks in cryptographic routines, and also that of `chars_base64/3` in `library(charsio)`.
> Performance improvements for library(crypto)

- src/clause_types.rs
- src/lib/builtins.pl
- src/machine/system_calls.rs
This allows switching standard output to binary, using for example:
?- current_output(S0), open(stream(S0), write, S, [type(binary)]).
`format/3` can then be used to write binary data to S. This is needed
for example when piping binary data to other programs.
This addresses #614, please read the discussion for more information.
The current implementation is very preliminary: Specifically, it works
by destructively modifiying the parameters of the underlying stream,
making it no longer usable in its original mode. Currently, if the
type of standard output is set to binary, then the toplevel no longer
works. Therefore, after writing binary output to standard output,
the program should either halt, or set the stream type back to text.
> ENHANCED: open/4 to allow opening a stream by specifying stream(S).

- src/lib/charsio.pl
This is useful in various applications to read more bytes or characters at once, such as in the web server library.
> ADDED: read_n_chars/3, reading N characters from a stream.

- tests/scryer/helper.rs
> pass -f to scryer-prolog in cargo test so that we ignore .scryerrc

- README.md
- src/lib/builtins.pl
- src/lib/format.pl
- src/lib/pio.pl
Most notably, this pull request adds **`phrase_to_stream/2`** to `library(pio)` so that we can transparently write strings described by a grammar rule body to a *stream*.
Further, it expresses `phrase_to_file/2`, `format/3` and `portray_clause/2` in terms of this new predicate, and also adds the new nonterminal `portray_clause_//1` (in analogy to `format_//2`), so that formatted Prolog programs can appear conveniently as part of a DCG.
`phrase_to_stream/2` seems to be one of the most fundamental building blocks for pure output, and will also come in handy when writing output to network sockets, such as in the HTTP server. @aarroyoc, I hope you find this useful!
> Various improvements for pure output

- src/lib/format.pl
With this fix:
```text
?- use_module(library(terms)).
true.
?- use_module(library(format)).
true.
?- T = a(A,B,A), numbervars(T, 0, _), format("~w", [T]), nl.
a(A,B,A)
T = a('$VAR'(0),'$VAR'(1),'$VAR'(0)), A = '$VAR'(0), B = '$VAR'(1).
?- T = a(A,B,A), numbervars(T, 0, _), format("~q", [T]), nl.
a(A,B,A)
T = a('$VAR'(0),'$VAR'(1),'$VAR'(0)), A = '$VAR'(0), B = '$VAR'(1).
```
Fixes #1081.
> Fix the format/2-3 predicates missing the numbervars(true) option in the ~w and ~q formats

- src/lib/reif.pl
This corrects a few arguments, and consistently uses round brackets in `meta_predicate/1` declarations because `meta_predicate` is not a standard operator.
> Meta predicate corrections

- src/lib/pio.pl
`phrase_from_file/3` exists, so it makes sense that `phrase_to_file/3` also exists
> Add phrase_to_file/3 (phrase_to_file with Options)

- src/lib/format.pl
Importantly,, the documentation now mentions the new predicates from `library(pio)` to directly write strings described by DCGs to a file or stream.
> Various smaller improvements to library(format)

- src/lib/charsio.pl
- src/lib/crypto.pl
- src/lib/error.pl
These constructs use internal features of Scryer Prolog for fast string tests that fit well into the general `must_be/2` and `can_be/2` pattern.
With this pull request, I am also using `must_be(chars, ...)` to simplify code in `library(crypto)` and `library(charsio)`, and also to make it more correct.
> New type tests: must_be(chars, ...) and can_be(chars, ...)

- src/lib/http/http_open.pl
- src/lib/sgml.pl
- src/lib/time.pl
- src/lib/xpath.pl
This pull requests changes a few definitions and occurrences of `list//1` to `seq//1` and `... //0`, which are now available in `library(dcgs)`.
> Use newly available seq//1 and ... //0 in several libraries

- crates/prolog_parser/src/parser.rs
I've tried to fix https://github.com/mthom/scryer-prolog/issues/721
Now, it doesn't panic in the examples in the issue but I do not know if this is the right fix or there's something flawed inside that needs to be changed so these checks aren't neccesary.
> Prevents panic in some strange cases. Seen in #721

- src/lib/builtins.pl
> ENHANCED: Character type checks for get_char/[1,2].

- src/loader.pl
This is in response to #1114. Note that
```
?- expand_goal(m:(length(_,_),true),m,G1).
G1 = m:(length(_A,_B),true).
```
but
```
?- expand_goal(call((length(_,_),true)),m,call(G1)).
G1 = m:(m:length(_A,_B),m:true).
```
> Expand call goals as call goals so that goals in control constructs are qualified properly

- src/lib/builtins.pl
- src/loader.pl
- src/machine/system_calls.rs
The problem in https://github.com/mthom/scryer-prolog/issues/1103 was that sometimes an `Addr::Lis` was passed to the open systemcall while it only expects Atom, Char and PStr. Here, we remove any special handling, and we just call heap_pstr_iter, which manages multiple representations of strings. How do we manage atoms? By converting them to strings in the builtin predicate. That way, the code is more simple and straightforward.
Here's an example of accepting and rejecting situations.
```
?- open(45, read, S).
caught: error(domain_error(source_sink,45),open/4)
?- open("ab", read, S).
S = '$stream'(0x557ea00ac9f0).
?- open(ab, read, S).
S = '$stream'(0x557ea00c0da0).
?- open([a,b], read, S).
S = '$stream'(0x557ea01b51d0).
?- append("a", "b", F), open(F, read, S).
F = "ab", S = …
```
> Allow all kinds of string to be processed in open/4

- src/lib/charsio.pl
> ENHANCED: Correct type error for char_type/2.

- src/lib/time.pl
> ENHANCED: Better reporting for time/1.

- README.md
- src/clause_types.rs
- src/lib/sockets.pl
- src/machine/streams.rs
- src/machine/system_calls.rs
The new predicates `tls_server_context/2` and `tls_server_negotiate/3` can be used to negotiate TLS connections with clients for encrypted and authenticated communication.
The full potential of Scryer Prolog for creating TLS servers (such as for HTTPS) will be realized when it gets support for multiple threads.
@aarroyoc: I hope you find this useful for the HTTP server library!
> ADDED: Support for creating TLS servers.

- src/lib/time.pl
This installs a small correction to a comment in `library(time)` and updates the header.
> walltime --> CPU time

- src/lib/pio.pl
This installs a small improvement to `phrase_to_stream/2`.
> ENHANCED: Use newly available fast chars test from library(error).

- src/lib/time.pl
This addresses https://github.com/mthom/scryer-prolog/pull/1131#issuecomment-988670049 .
> report time with "s" instead of "seconds", in analogy to time(1)

- crates/prolog_parser/src/lexer.rs
This takes into account https://github.com/mthom/scryer-prolog/pull/1112#issuecomment-981540485.
Example:
?- X = 1_/**/2.
X = 12.
In addition, I have simplified a test (`new line char` is a `layout char`).
> ENHANCED: Support also comments in integers with underscores

- README.md
- src/clause_types.rs
- src/lib/http/http_open.pl
- src/lib/sockets.pl
- src/lib/tls.pl
- src/machine/system_calls.rs
This pull request adds client-side TLS negotiation over arbitrary streams with configurable host names for certificate verification.
Since there are now already 4 TLS-specific predicates, and they are not specific to network sockets (they can be used over arbitrary streams), I have moved them all to the new library **`library(tls)`** and adapted the other libraries accordingly.
In the future, I anticipate that even more predicates will become available in `library(tls)`, for example predicates that load *certificates*, and more options to control connections.
> ADDED: library(tls) for negotiating TLS connections

- src/lib/format.pl
Example:
?- format("~2U", [10^12]).
%@ 10_000_000_000.00   true.
> ADDED: format specifier ~NU, using underscores to separate groups of digits

- build.rs
- crates/instructions-template/src/lib.rs
- crates/static-string-indexing/src/lib.rs
- src/atom_table.rs
- src/lib.rs
[Outputs of Build Script](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) in the Cargo Book states that "Scripts should not modify any files outside of that directory"
Also adds a rerun-if instruction to the build scripts output to only rerun if something in src/ changes.
Changes to the build script or its dependencies still cause the build script to be recompiled and rerun.
> Generate into $OUT_DIR instead of src/

- README.md
I think it would be good to mention `rebis-dev` in the README, since so much nice development is now going on in the branch.
> add links to the rebis-dev branch and its announcement

- src/machine/system_calls.rs
This addresses #1215.
Is this correct? Please review, and merge if applicable. Many thanks!
> retain the string "[]" as is, instead of converting it to '[]' (i.e., "")

- src/lib/crypto.pl
This allows efficient decryption also of very large files and long strings.
It is usually highly advisable to stick to common and portable library predicates such as `append/3`. However, since `append/3` does not yet recognize this opportunity for improvement, I apply it manually in this case, so that also very large files can be efficiently decrypted using the compact internal string representation. 
Without this change, decrypting a 1&nbsp;GB file takes 48&nbsp;GB of RAM, whereas with this change, it only takes 2&nbsp;GB (one for the string, one for its copy with the appended&nbsp;tag).
> ENHANCED: library(crypto): Retain a compact internal representation of the ciphertext throughout decryption.

- src/lib/charsio.pl
- src/lib/files.pl
- src/lib/pio.pl
- src/lib/time.pl
Dear all,
unfortunately two predicates I requested for (#334) or added to (#1071) `library(charsio)` are not optimally named. Specificially:
- `read_term_from_chars/2` should have been called **`read_from_chars/2`** for compatibility with SICStus Prolog (in its `library(charsio)`) and GNU Prolog.
- `read_n_chars/3` should have been called **`get_n_chars/3`** because "read" is associated with reading general Prolog terms, whereas individual bytes and characters are always fetched with `get_...`.
I am filing this pull request to rename both predicates at once, to resolve this as soon as possible rather than later, when more applications are affected. The impact of this change should be rather limited: If you are using these predicates in your applications, please also consider …
> MODIFIED: Rename two predicates in library(charsio)

- src/toplevel.pl
I have previously overlooked this change due to the now resolved problem described in #1227!
> FIXED: toplevel to use (newly renamed) read_from_chars/2

- src/parser/lexer.rs
To try it:
```
?- [user].
socrates.
<C-d>
?- socrates.
true.
?- <C-d>
(exits Scryer Prolog)
```
> Fix Ctrl-D in toplevel

- src/loader.pl
I think the preceding patch can be simplified like this, because the goals are already module-qualified. Please review, and merge if applicable. Many thanks!
> omit module prefix, because the goals are already module-qualified

- src/machine/system_calls.rs
`library(sgml)` now works correctly in `rebis-dev`.
> FIXED: load_html/3: use str_loc_as_cell! to store attribute structures

- src/toplevel.pl
Example:
?- member(X, "hello").
%@    X = h   <-- press "a"
%@ ;  X = e
%@ ;  X = l
%@ ;  X = l
%@ ;  X = o
%@ ;  false.
This improvement was recently also added to Trealla Prolog: https://github.com/trealla-prolog/trealla/issues/475.
> ADDED: "a" to enumerate all solutions

- README.md
From [*Fifty Years of Prolog and Beyond*](https://arxiv.org/pdf/2201.10816.pdf), I get the impression that the section on strings would benefit from these clarifications, because the extreme extent and impact of this innovation still seems somewhat unclear currently.
> DOC: Better explanation of strings and partial strings.

- src/lib/builtins.pl
This pull request fixes the following queries:
```text
?- current_prolog_flag(max_arity, _).
false.
?- current_prolog_flag(bounded, _).
false.
```
> Fix querying the values of the bounded and max_arity flags

- src/lib/iso_ext.pl
> ENHANCED: call_nth(Goal, 0) now fails, correct error for N < 0.

- src/machine/args.rs
- src/machine/mod.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
- src/read.rs
- src/toplevel.pl
- tests/scryer/helper.rs
Flag prevents the input stream from saving terms to ~/.scryer_history when set. Use the flag when running tests to increase test isolation.
Created a machine args module to handle the flag as the input stream is initialized prior to the toplevel cjode being run. Used a very simple method of dealing with the arguments but a library could be used later if the complexity of the args increases.
Switch to using the recently implemented `ReadlineStream::reset` instead of recreating the stream and removed the `input_stream` function which was only used for that purpose from what I can tell.
Happy for any and all feedback on this.
> Add --no-add-history flag

- .github/workflows/test.yml
- Cargo.toml
Based on the feedback to https://github.com/mthom/scryer-prolog/issues/1335#issuecomment-1062039516 this adds the rust-verrsion field in Cargo.toml and a CI job to check that it is still accurate
> Set minimum rust version in Cargo.toml

- .github/workflows/test.yml
- Cargo.toml
Based on the feedback to https://github.com/mthom/scryer-prolog/issues/1335#issuecomment-1062039516 this adds the rust-verrsion field in Cargo.toml and a CI job to check that it is still accurate.
Follow-up to #1347 This time without breaking CI
> Set minimum rust version in Cargo.toml (Attempt 2)

- src/lib/files.pl
This makes file operations with Scryer Prolog a lot faster.
> ENHANCED: use newly available must_be(chars, ...), which is very fast

- Cargo.lock
- Cargo.toml
- build/instructions_template.rs
- src/arena.rs
- src/lib/http/http_open.pl
- src/machine/dispatch.rs
- src/machine/mock_wam.rs
- src/machine/mod.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
- src/macros.rs
This PR replaces the `http_open/3` library, based on Prolog and substitutes it with one with a Rust backend. This allows us to connect via HTTP/1.1, HTTP/2.0, ... without any trouble. It uses Hyper, which is the most common HTTP library in Rust. It also brings Tokio in, but it doesn't do anything fancy yet.
It adds a new read-only stream type, which I think it's fine given the importance of HTTP interactions.
Some things could still be improved, like input validation, redirects, and auth, but all of these can be done in Prolog in a future task.
Glad to hear your suggestions!
> Add Hyper based `http_open/3`

- .github/workflows/docker-publish.yml
- Dockerfile
I wanted to play with the Docker image a bit and noticed that I couldn't import `library(debug)`. After a while I realised that the Docker image was last updated two years ago. So I thought it might be helpful to setup a GitHub action for this project that automatically builds and pushes new images 🙂 
I’m not sure what the release workflow is here. These Git tags (v0.9.0 etc) are created manually, right? The GitHub action is configured to run whenever such a tag is created and uses that tag (without the leading “v”) as the Docker image tag. Also the `latest` tag is kept in sync with the most recent version. 
To make it work, two secrets must be added: `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`. They can be added under:
*[this repository] > Settings > Secrets > Actions > New repository …
> push Docker image on new release

- src/lib/error.pl
This terminology is a bit harder to understand than that of the other
type checks.
Scryer Prolog comprises two individually consistent but incompatible
notions of terms, namely terms and rational trees (which are also
called "cyclic terms"). This leads to a confusion in terminology,
because cyclic terms are not terms in the former sense even though
they also contain the word "term" in their name.
This terminological confusion is not restricted to terms: We also find
it for example in the notion of lists. Lists are defined inductively:
- The empty list (written as "" or [], called 'nil') is a list.
- A term with principal functor '.'/2 is a list if its second argument
is a list.
Note that a list may contain cyclic terms as elements, and still be
called a list. However, if we post:
?- Ls = …
> ADDED: can_be(term, ...) and must_be(term, ...)

- build/static_string_indexing.rs
- src/lib.rs
- src/machine/machine_state.rs
- src/machine/system_calls.rs
- src/read.rs
- src/repl_helper.rs
This pull request adds tab completion of predicates and highlighting of matching brackets to the repl. There is a lot of raw pointer use in order to get around the Stream abstraction, from what I could gather, in order to change this to safe rust, this abstraction would need to be changed and explicit life times added to a few structs. I think the dereferencing of pointers is all valid, but I am not certain due to my limited understanding of the code base. I also think there are a few atoms in the `atom_tbl` which we do not want in the completion list, such as the directory of the executable, but I could not find a way to filter them out.
> Completion of predicates in repl

- src/lib/error.pl
This should simplify 2f3de51e554629d2e7b4ea023c9ef181c240692c and other cases like it.
> FIXED: can_be(chars, [a,X]), i.e., if variables occur as elements

- README.md
This feature, added via https://github.com/mthom/scryer-prolog/pull/1467, makes the toplevel interaction a lot more convenient in many cases.
Many thanks to @euanlacy!
> document atom and predicate completion with TAB

- src/lib/sgml.pl
Notably, stronger and better error handling.
The new domain error (instead of failing silently) is especially helpful when the `stream/1` wrapper is accidentally omitted in queries.
> Various improvements to library(sgml)

- build/main.rs
- when rustfmt is not detected (by attempting to run ``rustfmt --version)
no formatting will be attempted
- this should resolve issue mthom/scryer-prolog#1504
> make rustfmt optional

- .gitattributes
- this should stop problems such as mthom/scryer-prolog#1491 ,
by specifying the line ending, as this should take precedence over the global config
Note: depending on whether `\r\n` line endings should be supported this might just hide the symptoms instead of fixing the underlying problem
> add a .gitattributes file

- src/arena.rs
- src/machine/heap.rs
- src/parser/ast.rs
- src/parser/mod.rs
- src/parser/parser.rs
Previously building with `cargo build --no-default-features --features num` was basically useless because the imports were not set up correctly. 
It still doesn't work though, but that's not because of this project.
> Fixed imports for num-rug-adapter

- src/lib/clpz.pl
I need to step up my game to stay competitive with the most recent performance improvements in the `rebis-dev` branch!
These changes yield an up to 3-fold performance improvement on tasks that use `all_distinct/1` heavily, such as Sudoku puzzles, *on top* of the roughly 6-fold improvement due to inlining.
This means that in total, several Sudoku puzzles are now solved about **18 times faster** with the `rebis-dev` branch.
> CLP(ℤ) performance improvements

- Cargo.lock
- Cargo.toml
- build/instructions_template.rs
- src/arena.rs
- src/http.rs
- src/lib.rs
- src/lib/http/http_server.pl
- src/machine/dispatch.rs
- src/machine/mod.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
- src/macros.rs
This is the updated version of `library(http/http_server)`. It doesn't add any new feature on the API side (which keeps compatibility) but uses a completely different approach under the hood, by using the Hyper library (same as `library(http/http_open)`.
For a test, I share you my testing file:
```prolog
:- use_module(library(http/http_server)).
:- use_module(library(lists)).
:- use_module(library(dcgs)).
:- use_module(library(format)).
text_handler(Request, Response) :-
http_status_code(Response, 200),
http_body(Response, text("Welcome to Scryer Prolog!")).
sample_handler(Request, Response) :-
http_headers(Request, Headers),
member("user-agent"-UserAgent, Headers),
http_body(Response, text(UserAgent)).
sample_body_handler(Request, Response) :-
http_body(Request, bytes(Body)), …
```
> HTTP Server 2.0

- src/lib/lists.pl
This is now possible due to 4c7e2eb8614da9c04f2286f6116b468017fb442c.
See #1529 for the suggestion by @UWN.
<s>**Warning**: *This does not yet work.* Which the patch applied, I get:
<pre>
<b>$ scryer-prolog</b>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError(ParserError(IncompleteReduction(252, 0)))', src/machine/mod.rs:500:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</pre></s>
**Update**: This works as intended now. Example:
<pre>
<b>?- nth0(3, "abcdefg", E).</b>
E = d.
</pre>
> ENHANCED: Use '$skip_max_list'/4 for greater efficiency of nth0/3.

- src/lib/charsio.pl
- src/lib/crypto.pl
- src/lib/error.pl
- src/lib/pio.pl
See https://github.com/mthom/scryer-prolog/discussions/1555 and https://github.com/mthom/scryer-prolog/issues/1309.
> New types for library(error): octet_character, octet_chars

- src/lib/clpz.pl
- src/lib/error.pl
- src/lib/lists.pl
- src/lib/simplex.pl
This also adds `nth0/4` and bootstraps `nth1/[3,4]` from it.
> ENHANCED: Much improved nth0/3, taken from #1529.

- Cargo.lock
- Cargo.toml
- build/instructions_template.rs
- src/lib/crypto.pl
- src/machine/system_calls.rs
This is achieved by using the newly available crrl crate by @pornin
to implement `crypto_curve_scalar_mult/4` for secp256k1. Many thanks!
> ENHANCED: Eliminate the OpenSSL dependency of library(crypto).

- src/lib/crypto.pl
- src/machine/system_calls.rs
Here are a few smaller improvements and simplifications, mostly by introducing and using a new function `u8s_to_string` to convert an array of `u8` to a compact Prolog&nbsp;string.
> Smaller improvements

- Cargo.toml
I noticed that CI is failing because the version declared no longer actually works.
So this PR adjusts the declared rust-version to to the earliest working one.
> Adjust rust-version

- src/machine/arithmetic_ops.rs
If first argument n1 in xor/2 is of wrong numerical type, the match patterns fall through to a catch all case that reports the second argument in the type error.
Fixes #1626
`xor/2 function reports the wrong argument in type error #1626`
https://github.com/mthom/scryer-prolog/issues/1626
> Fix xor/2 type error reporting wrong argument

- src/machine/system_calls.rs
According to ISO Prolog, get_byte/2 predicate can receive an instantiated input byte:
http://www.gprolog.org/manual/html_node/gprolog037.html#sec156
get_byte(+stream_or_alias, ?in_byte)
Since in_byte can be -1 if EOF is reached, instantiating it with -1 should work but does not because the implementation is trying to convert it to a u8 which is unsigned:
?- open("/dev/null", read, S, [type(binary)]), get_byte(S, -1).
error(type_error(in_byte,-1),get_byte/2).
This commit adds an extra check for -1 before checking for a valid u8 instantiated value if in_byte is an input:
?- open("/dev/null", read, S, [type(binary)]), get_byte(S, -1).
S = '$stream'(0x55601e65c998).
Closes #1625
> fix type_error with instantiated EOF -1 byte literal in get_byte/2

- .github/workflows/docker-publish.yml
I adjusted the docker-publish job to run on every push to master and update the `latest` tag Docker Hub. As before, all pushed git tags should also trigger the job and publish Docker images tagged with the corresponding version. I tested this on my fork and there it worked:
* [job triggered by push to master](https://github.com/gruhn/scryer-prolog/actions/runs/3472917386) and [resulting docker image](https://hub.docker.com/layers/gruhn/scryer-prolog/latest/images/sha256-749e26f4e08d06da53e9ddd06350c8b67da119e245c00512731436bdd0f10cf7?context=repo)
* [job triggered by push of git tag](https://github.com/gruhn/scryer-prolog/actions/runs/3481417402) and [resulting docker image](https://hub.docker.com/layers/gruhn/scryer-prolog/0.0.12/images/sha256-1e28835dadc2c6ed6eb9d86dc91dde70c41ca22152a98 …
> Adjust Github Action: Docker Publish

- src/machine/system_calls.rs
See also #1654 for a nice test case by @notoria which this corrects.
> dereference more registers, analogous to d660e4244ff48bbcd558fab07a4dd4a5e9d68209

- build/instructions_template.rs
- src/lib/files.pl
- src/machine/dispatch.rs
- src/machine/system_calls.rs
This PR adds the copy_file/2 predicate to library(files). This predicate uses [std::fs::copy](https://doc.rust-lang.org/std/fs/fn.copy.html) underneath which is optimized for each operating system.
> Add predicate file_copy/2 in library(files)

- src/lib/assoc.pl
- src/lib/clpb.pl
- src/lib/files.pl
- src/lib/http/http_open.pl
- src/lib/iso_ext.pl
- src/lib/lists.pl
- src/lib/ordsets.pl
- src/lib/random.pl
- src/lib/sockets.pl
- src/lib/ugraphs.pl
- src/lib/uuid.pl
Migrate several libs to Markdown docs to Djot docs. Djot reference syntax is here: https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#heading However, not all features described there are implemented in Djota right now.
> Migrate from Markdown to Djot

- Dockerfile
Apparently [the Docker build is failing again](https://github.com/mthom/scryer-prolog/actions/runs/3916277566/jobs/6695250146). With the error:
> error[E0658]: use of unstable library feature 'scoped_threads'
I don't know what that means but [a guy on StackOverflow claims, that this issue does not occur with Rust 1.63 anymore](https://stackoverflow.com/questions/74692232/cargo-use-of-unstable-library-feature-scoped-threads). 
I set the Rust version in the Dockerfile to the latest minor release now (currently 1.66). When I test it locally the build succeeds again.
> Fix failing Docker build

- src/lib/between.pl
Added documentation for `library(between)`
> Compatible Doclog docs for library(between).

- src/lib/os.pl
Added documentation for predicates in `library(os)`
> Compatible Doclog docs for library(os)

- src/lib/xpath.pl
Reformatted documentation of `library(xpath)`
> Compatible Doclog docs for library(xpath).

- src/lib/sgml.pl
This is for the upcoming Scryer Prolog website.
> DOC: convert library(sgml) documentation to DocLog format

- src/lib/time.pl
This is for the upcoming Scryer Prolog website.
> DOC: convert library(time) documentation to DocLog format

- src/lib/crypto.pl
This is for the upcoming Scryer Prolog website.
> DOC: convert library(crypto) documentation to DocLog format

- src/lib/clpb.pl
- src/lib/clpz.pl
This provides basic user-facing documentation to be shown on the Scryer documentation site when it becomes available.
@aarroyoc: Could you please take a look at the CLP(B) documentation I am adding with this pull request? I have tried to process this with the current version of `doclog`, and notably the table is currently not formatted as intended.
Thank you a lot!
> DOC: preliminary CLP(B) documentation in DocLog format

- src/lib/debug.pl
This is for the upcoming Scryer Prolog homepage.
> DOC: add DocLog documentation for library(debug)

- src/lib/diag.pl
This is for the upcoming Scryer Prolog homepage.
> DOC: add DocLog documentation for library(diag)

- src/machine/arithmetic_ops.rs
If a number can't be converted to u32 (possibly negative) try to convert first to u32 the inverse number and switch the operation (right -> left, left -> right).
> Negative shifts (fixes #1719 and #1718)

- README.md
This is a minor change that some readers might find quite helpful. Note that some references are already linked farther down in the README.md. 
This PR is, I propose, a prelude to another PR that creates a bibliography for the project and reorganizes the WAM book as an item "beneath" the bibliography (with whatever emphasis that particular source deserves). Several papers and at least one book are referenced in the project. It seems like a natural addition to me. (I argue that the bibliography should collect whatever references the Scryer-Prolog authors have found helpful, but that's up to other people to decide.) Would such a PR be welcome?
> Added links to referenced research papers in the Phase 2 and Nice to Have Features sections.

- src/lib/clpb.pl
- src/lib/clpz.pl
This is to avoid duplicated goals with the new projection mechanism.
> in projection of residual goals, mark considered propagators as processed

- src/lib/clpz.pl
This great improvement to indexing allows much more natural definitions of virtually all meta-predicates. Many thanks to @notoria!
> rely on first instantiated argument indexing

- src/lib/clpz.pl
This reduces the number of attributed variables remaining after propagation.
> Better queue

- src/toplevel.pl
Example:
?- freeze(_, false).
freeze:freeze(_A,false).
This was originally added in 04ba9bc11af31780cd8fa259d78d151262c3c756, then reverted, and is now restored.
> ENHANCED: use call_residue_vars/2 to show all pending constraints

- README.md
This is motivated by a recent question on the `#scryer` IRC channel, "how can I run the scryer interpreter?", and, compellingly, "`scryer-prolog` is an unknown command".
In addition to explaining where the `scryer-prolog` executable is, this changes the documentation to use `cargo build` instead of `cargo run` so as to avoid unexpected invocation of the system, and decisively uses the `--release` flag so that the instructions can be used verbatim and the now documented path of the executable is correct.
> Smaller documentation improvements to explain compilation and target directory

- .github/workflows/test.yml
- Cargo.toml
- README.md
- scryer-prolog.wxs
Hi! I was inspired to make improvements to the build/Test action, so here's a PR with the results.
The overall theme is reducing typical build and test times so contributors can iterate on PRs faster, and adding some nice-to-have build pipeline features like linting and publishing temporary build artifacts.
* Use `actions/cache@v3` action to cache builds of dependencies between runs to improve build times.
* This means that the first build result is back in 2:40 (down from 12:00), the full job is completed in 16:00 (down from 25:00), and total 'vm time' is reduced from 1:45:00 to 40:00.
* The cache is keyed off of `os + rustc version + cargo.lock contents`, so it should be invalidated correctly.
* That said there is still a risk of cache issues. It's pretty easy to clear the cache though, …
> Optimize Test GH action

- .github/workflows/test.yml
Based on discussion #996, installs @pmoura's logtalk3 and runs the prolog tests at the end of the `build (ubuntu-20.04, stable, bash)` job. Hopefully this would highlight changes that reduce iso compatibility before they cause a regression.
Other changes:
* switch to macos-11 image, the macos-10.15 is officially deprecated by github actions
* Misc cleanup
Here is an example run: https://github.com/infogulch/scryer-prolog/actions/runs/4591169519/jobs/8107155034
This increases the runtime of the selected job by 11 minutes, but since it runs in parallel with other jobs it doesn't change the overall walltime of the workflow. I think this is worth it.
> Add iso prolog / logtalk tests to test runner

- src/lib/clpz.pl
Example:
?- tuples_in([[A,A]],[[0,1],[2,0]]).
false.
See https://github.com/triska/clpz/issues/22.
> FIXED: propagation for ground tuples

- src/lib/charsio.pl
- src/machine/system_calls.rs
It adds uppercase and lowercase transformations based on #748 
```
?- use_module(library(charsio)).
true.
?- char_type(x, Type).
Type = alnum
;  Type = alpha
;  Type = alphabetic
;  Type = alphanumeric
;  Type = ascii
;  Type = ascii_graphic
;  Type = lower
;  Type = octet
;  Type = prolog
;  Type = symbolic_hexadecimal
;  Type = to_lower("x")
;  Type = to_upper("X")
;  false.
?- char_type('ß', Type).
Type = alnum
;  Type = alpha
;  Type = alphabetic
;  Type = alphanumeric
;  Type = lower
;  Type = octet
;  Type = prolog
;  Type = to_lower("ß")
;  Type = to_upper("SS")
;  false.
?- char_type('X', Type).
Type = alnum
;  Type = alpha
;  Type = alphabetic
;  Type = alphanumeric
;  Type = ascii
;  Type = ascii_graphic
;  Type = octet
;  Type = prolog
;  Type = to_lower("x")
;  Type = …
```
> library(charsio): add to_upper and to_lower

- .github/workflows/ci.yml
I worked with the author of the `publish-unit-test-result-action` to deliver an enhancement that makes it work better for the scryer-prolog project, but I forgot to scrub the testing branch reference out of the action before it was merged. This is the cause of some of the [recent PR builds failing](https://github.com/mthom/scryer-prolog/actions/runs/4771903258/jobs/8484131136?pr=1792#logs):
> Error: Unable to resolve action `EnricoMi/publish-unit-test-result-action@branch-publish-summary-on-fork`, unable to find version `branch-publish-summary-on-fork`
This changes it to use the master branch again. Sorry!
> Change ref for `publish-unit-test-result-action`

- .github/workflows/ci.yml
This probably appeared now because it's the first time this tool was cached from a previous run.
This should fix the build for PR 1794: https://github.com/mthom/scryer-prolog/actions/runs/4774317135/jobs/8487922812?pr=1794
> Use --force to install cargo2junit

- src/lib/si.pl
Source: https://stackoverflow.com/questions/20223390/prolog-a-person-is-a-sibling-of-himself
In Scryer Prolog, this is actually not needed, since Scryer Prolog provides dif/2 in library(dif). However, it is still useful to provide dif_si/2 for two reasons:
1) to more easily port code from systems where only dif_si/2 is available
2) to provide correct disequality in other systems that adopt this library
> ADDED: dif_si/2

- src/machine/system_calls.rs
Now:
```
?- use_module(library(charsio)).
true.
?- char_type(a, X).
X = alnum
;  X = alpha
;  X = alphabetic
;  X = alphanumeric
;  X = ascii
;  X = ascii_graphic
;  X = hexadecimal_digit
;  X = lower
;  X = octet
;  X = prolog
;  X = symbolic_control
;  X = to_lower("a")
;  X = to_upper("A")
;  false.
?- char_type(a, to_upper("A")).
true.
?- char_type(a, to_upper("B")).
false.
?- char_type(a, to_upper('A')).
false.
?- char_type(a, to_upper([X])).
X = 'A'.
```
> Fix to_upper/to_lower when string is instantiated

- src/heap_print.rs
Example:
?- X = '\xa0\'.
X = '\xa0\'.
This addresses #1768.
> FIXED: consistent read/write of further control characters, and non-breaking space

- src/parser/macros.rs
Example:
?- X = "ↁ".
X = "ↁ".
This addresses #1790.
> ENHANCED: allow Roman numerals in strings

- src/lib/lists.pl
This allows shorter and more natural definitions.
> rely on first instantiated argument indexing in the definitions of foldl/N

- src/machine/system_calls.rs
> FIXED: correct dereferencing in atom_codes/2 and number_codes/2.

- src/lib/charsio.pl
Dear all,
in continuation of #1228, this PR renames the last remaining erroneously called "read..." predicate to **"get..."**, namely **`get_line_to_chars/3`**.
The only currently existing use of this predicate I am aware of occurs in [`newscryer.pl`](https://www.metalevel.at/prolog/faq/newscryer.pl), which I hope is the only program that needs to adapt.
Please adjust your programs if necessary, and forgive the backwards incompatible change.
Thank you and all the best,
Markus
> MODIFIED: read_line_to_chars/3 is now called get_line_to_chars/3

- .github/workflows/ci.yml
Changes the CI trigger to automatically create release when a tag that matches `v*` is pushed to the repo.
Also bumps MSRV to 1.65, because  [the version of rug in cargo.lock was increased to 1.19](https://github.com/mthom/scryer-prolog/commit/7f45ac3f7a947e3d7b6556cddea9110622b675fd#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL1611-L1616), which [only supports rust 1.65 and newer](https://gitlab.com/tspiteri/rug#version-1190-news-2023-01-06). This was causing the build to fail.
> Fix tags trigger; bump MSRV to 1.65

- src/toplevel.pl
Here are a few further improvements to `needs_bracketing/2`.
Notably, we now get for example:
<pre>
<b>?- X = -->(a,b,c).</b>
X = -->(a,b,c).
</pre>
Also, I removed 2 branches that I think are not necessary.
In addition, I have switched the if-then-else to disjunctions to make the code shorter and more readable, without introducing any non-determinism in the toplevel itself, because `needs_bracketing/2` is always used in a "cutting" context, where alternative solutions are not considered anyways.
> Improvements to needs_bracketing/2

- build/instructions_template.rs
- src/heap_print.rs
- src/lib/builtins.pl
- src/lib/charsio.pl
- src/machine/machine_state.rs
- src/machine/mock_wam.rs
- src/parser/ast.rs
- src/toplevel.pl
- tests-pl/iso-conformity-tests.pl
- tests/scryer/src_tests.rs
The ISO syntax conformity tests of [https://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/conformity_testing) are here introduced as Prolog predicates run by the `run_tests/0` predicate. 
Currently, none of the tests fail when `-f` is used on this branch.
> Automate ISO syntax conformity tests

- src/machine/machine_state_impl.rs
- src/types.rs
It fixes https://github.com/mthom/scryer-prolog/issues/1855 by giving stream terms a way to be compared similar to atoms and compounds.
> Allow comparisons with stream terms

- src/heap_print.rs
- tests-pl/iso-conformity-tests.pl
- tests/scryer/issues.rs
This is in response to #1860. Some tests may now be wrong, please review. #135 is unclear to me, `writeq` prints `-(1)` under this PR branch.
> Revise iso_conformity_tests.pl to remove unnecessary spaces

- src/heap_print.rs
- src/machine/machine_state.rs
- src/machine/mock_wam.rs
- src/toplevel.pl
This gives consistent results without depending on another flag.
I think this semantics is better, since it gives more predictable results, and it also simplifies the internal implementation, letting us move more of the logic to Prolog.
Also, it now behaves as it was already documented.
> make double_quotes write option not dependent on double_quotes flag

- Cargo.lock
- Cargo.toml
- src/http.rs
- src/lib/http/http_server.pl
- src/machine/streams.rs
- src/machine/system_calls.rs
* use reqwest for http_open (still uses Hyper underneath)
* use Hyper 1.0.0-rc3 for server
* Modify all internal handling of server
In general we try to use less parts of Tokio (which can be problematic right now and actually it introduced a complex data race) while preparing Scryer to use Hyper 1.0 once it reaches final state. We use reqwest instead of Hyper for the client because in Hyper 1.0 they removed the high-level Client module we were using, reqwest is from the same authors, higher level but for our use case, still fine.
Note that none of this changes the external API that http_open and http_server define.
> Multiple fixes for http libraries

- build/instructions_template.rs
- src/codegen.rs
- src/lib/lists.pl
- src/machine/dispatch.rs
- src/machine/machine_state.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
- src/targets.rs
Please try out this PR. It would be better to catch segfaults before merging.
> use lookahead to skip inapplicable clauses (#1028, #1502)

- src/lib/iso_ext.pl
Example:
?- countall(member(X, "abc"), N).
N = 3.
> ADDED: countall/2, for compatibility with GNU Prolog.

- Cargo.lock
- Cargo.toml
- src/atom_table.rs
- tests/scryer/issues.rs
The AtomTable currently uses a global variable to store the pointer to the AtomTable's block base. This means that only one AtomTable can be used at once as otherwise Atoms may be looked up in the wrong AtomTable. This PR adds logic to detect an AtomTable being created while one already exists. When this is detected it panics with a descriptive error message, to prevent more obscure problems.
> detect and prevent concurrent AtomTable use

- src/lib/clpz.pl
This addresses the issue raised in https://github.com/mthom/scryer-prolog/discussions/1937.
> ENHANCED: forget auxiliary constraints set up by the propagator for multiplication

- src/lib/xpath.pl
This removes leading and trailing whitespace from the text. Whitespace within the string is not yet considered.
> ENHANCED: rudimentary implementation of normalize_space

- src/lib/builtins.pl
- src/toplevel.pl
This lets us specify additional write options used by the top level for writing answers.
> ADDED: New Prolog flag, answer_write_options.

- src/lib/clpb.pl
Example:
?- sat(A+B), weighted_maximum([1,1], [A,B], Max).
A = 1, B = 1, Max = 2.
> remove clpb_max/1 attribute for residual goal projection

- src/lib/builtins.pl
Quoting from 7.11 Flags:
NOTE - A built-in predicate current_prolog_flag(Flag, Value)
(8.17.2) enables a program to discover all the flags supported
by a processor and their current values.
> FIXED: make occurs_check and answer_write_options flags discoverable

- Cargo.toml
- README.md
- build/instructions_template.rs
- src/atom_table.rs
- src/lib.rs
- src/machine/dispatch.rs
- src/machine/mock_wam.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
Currently 6/12 crypto functions supported. Tested in browser with all default features disabled.
> Basic WebAssembly support with minimal Javascript API #615

- Dockerfile
The Docker image is broken with the error message:
scryer-prolog: error while loading shared libraries:
libssl.so.1.1: cannot open shared object file: No such
file or directory
We use the base base image `debian:stable-slim` and in the background a new Debian version was marked stable (bookworm), which has libssl3 instead of libssl1.1 installed.
I downgraded the base image to the previous stable version (bullseye), which seems to fix the issue.
> fix Docker image

- src/machine/mock_wam.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
Until now, set_random wasn't really useful (#1985) because we were not using that random generator in `maybe/0`. With this, we can get deterministic random numbers based on a seed. By default, it will just take a seed from the system, as before.
```
?- use_module(library(random)).
true.
?- random_integer(0, 100, N).
N = 13.
?- set_random(seed(42)).
true
;  ... .
?- random_integer(0, 100, N).
N = 57.
?- random_integer(0, 100, N).
N = 21.
?- random_integer(0, 100, N).
N = 55.
?- set_random(seed(42)).
true
;  ... .
?- random_integer(0, 100, N).
N = 57.
?- random_integer(0, 100, N).
N = 21.
?- random_integer(0, 100, N).
N = 55. 
```
> Use a SeedableRng to generate random numbers

- src/machine/mock_wam.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
`maybe` can be a one-liner. Noticed when casually browsing #2025.
Also fixes some whitespace errors.
> Simplify fn maybe

- src/lib/dif.pl
- src/tests/dif.pl
- tests-pl/dif_tests.pl
- tests/scryer/src_tests.rs
These changes make so that `dif/2` passes all [these tests](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dif). I made a test battery to check that and it's included with this PR. 
Honestly, I don't really understand what I did here. I guess it involves removing the involved goals from the `dif/1` attribute and then reapplying them with `dif/2` after the unification. Doesn't look very efficient. I also feel I may have broken something else while doing it, but at least the tests pass.
Closes #1382.
Closes #1433.
Closes #1956.
> Improvements to dif/2

- .github/workflows/ci.yml
See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
> Allow all matrix ci jobs to run to completion even if one fails

- src/lib/pio.pl
I wanted to learn how to use global variables in Prolog (`bb_get/2` and `bb_put/2` specifically), and thought this was a good application. It was very, _very_ hard but I think I did it.
In my opinion `phrase_from_stream/2` is the most useful predicate that wasn't yet implemented. I already stumbled into many situations where it would have been incredibly useful, mainly dealing with sockets.
In this implementation it still uses the old `stream_to_lazy_list/2` for repositionable streams, as I bet it's way more efficient than whatever shenanigans I'm doing in the other case, especially for large files. For non-repositionable streams it stores the data from the string in a buffer to enable backtracking, as suggested in #1146.
I'm not sure if this can handle arbitrary binary data, as it uses …
> Add phrase_from_stream/2 to library(pio)

- .github/workflows/ci.yml
See: #1998, #2047
Example build: https://github.com/infogulch/scryer-prolog/actions/runs/6323046069
Notably, the windows build result is much smaller, ~10MB instead of ~100MB, which is nice.
> Build windows with msvc #1998; add ubuntu 22.04 target #2047

- Cargo.lock
- Cargo.toml
- README.md
- build/instructions_template.rs
- src/http.rs
- src/lib/http/http_server.pl
- src/machine/dispatch.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
Changes:
- Use Warp instead of Hyper (Warp still uses Hyper underneath, but manages more things for us)
- Optimize clones
- HTTPS support, just by passing a key and a certificate
- Content-Length limit
- HTTP Basic Auth
- Stop server with Ctrl-C
> Replace Hyper with Warp for HTTP server

- src/lib/clpz.pl
Example:
?- X = 0, Y = 0, Z #= X-1 + Y-1.
X = 0, Y = 0, Z = -2.
This addresses #2064.
See ca5a5b4392bfbed8cfdbb3b2e7dbaa42ea193007 for a previous issue in this logic.
> FIXED: corrections to expansion_simpler/2

- .github/workflows/ci.yml
Also note how to disable the job when necessary in the future.
> Pin logtalk to version before scryer support was removed

- src/lib/clpz.pl
If reification constraints (such as reified equality) are triggered here, then they may wish to disable this propagator and remove attributes from auxiliary variables. If the pexp/3 propagation is interrupted for that purpose, then the attributes will be unintentionally reattached by the following fd_put/3 calls in this propagator. We must ensure that this propagator completely finishes, so we queue the triggered propagators for later processing.
geq/2 implements propagator activation outside the queue, and thus should not be used in propagators in the way it was used here.
pexp/3 by itself may not seem particularly important. However, it can arise by metamorphosis from Var*Var. Example:
?- A#<==> -1#=C*C, C in 0..1.
A = 0, clpz:(C in 0..1).
This addresses #2089.
@notoria: This may be …
> FIXED: Queue triggered propagators to be processed after pexp/3 finishes

- src/lib/clpz.pl
Example:
?- #\ 0#=(Y// -1)/0.
%@    clpz:(Y in inf..sup).
This addresses #2104.
> ENHANCED: Omit unnecessary residual constraints in disentailed reified (//)/2

- .github/workflows/ci.yml
This makes wasm build separately as its own architecture target in the build matrix, and compiles directly instead of using wasm-pack.
⚠️ This also changes the test step to not fail the build because it currently fails on wasm. ⚠️
I think this is a reasonable intermediate step until the wasm tests are fixed, after which we can remove the `|| echo "::warning` at the end of line 66 so that failing tests will fail the build again.
In particular, I would expect this command to succeed without producing any errors or warnings:
```
cargo test --target wasm32-unknown-unknown --no-default-features --all --verbose
```
> CI: compile wasm separately; default 22.04; matrix

- src/lib/charsio.pl
- src/machine/system_calls.rs
From discussion here: https://github.com/mthom/scryer-prolog/discussions/2129
> Rename `to_upper` to `upper` and `to_lower` to `lower`

- .github/actions/setup-rust/action.yml
- .github/actions/setup-rust/cleanup.sh
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- benches/README.md
- benches/edges.pl
- benches/numlist.pl
- benches/run_criterion.rs
- benches/run_iai.rs
- benches/setup.rs
- src/codegen.rs
- src/debray_allocator.rs
- src/forms.rs
- src/machine/lib_machine.rs
This PR is an idea for how we can add benchmarks to scryer-prolog. The ultimate goal would be to have an array of benchmarks and publish a report that displays the measurements over time. But first things first...
The challenge of running benchmarks on public runners like GitHub Actions is that the variation in wall clock time can be as high as 20% due to environment differences out of your control like noisy vm neighbors. This obliterates the utility of using automated benchmark results to judge whether a proposed change actually helps performance.
So this PR pursues a strategy of measuring the *number of instructions executed* during the benchmark. Unlike wall time this metric is very stable and sometimes even deterministic. Admittedly the instructions executed metric is only …
> Add benchmarks

- .github/workflows/ci.yml
This should allow dependabot builds to complete, see #2159
> Add checks permission to ci workflow

- src/lib/time.pl
<s>I'm marking this as a draft because it does not yet show the number of inferences when the goal fails.</s>
> ENHANCED: time/1 now shows the number of inferences

- Cargo.lock
- Cargo.toml
- build/instructions_template.rs
- src/forms.rs
- src/lib.rs
- src/lib/wasm.pl
- src/machine/dispatch.rs
- src/machine/system_calls.rs
Adds a `js_eval/2` predicate for wasm32. It's the most simple way of achieving FFI on WASM. It takes a JavaScript snippet that gets executed in the platform `eval` function. Whatever gets evaluated gets returned to the Prolog side. Mapping right now is only supported with strings, numbers, booleans and the special values null and undefined.
> Add js_eval/2 for wasm32

- Cargo.toml
- src/machine/system_calls.rs
As shown [here](https://github.com/aarroyoc/scryer-playground/issues/11), $cpu_now/1 was missing an implementation for wasm32, making the time/1 predicate unusable. This adds an implementation for it.
> Implement $cpu_now in wasm32

- src/lib/si.pl
One use case is to ensure that once/1 is safe to use:
term_si(Goal),
once(Goal)
In such cases, Goal is ground and can yield at most one solution, therefore once/1 does not remove any solutions.
> ADDED: term_si/1, true for terms

- src/parser/macros.rs
Add '%' to `graphic_char` macro, to be consistent with `is_ascii_graphic`.
Fixes #2199 (Probably should have just opened the PR by itself)
> Add '%' to the list of graphic_chars (#2119)

- src/parser/macros.rs
Reverts mthom/scryer-prolog#2200
My mistake, apparently this does not conform to the standard: https://github.com/mthom/scryer-prolog/issues/2199#issuecomment-1837892004
> Revert "Add '%' to the list of graphic_chars (#2199)"

- .github/workflows/ci.yml
This makes the output of the test step more easily readable.
> CI: Make test step output easier to read

- src/lib/clpb.pl
- src/lib/clpz.pl
That syntax must be in a code block, so escaping functionality is disabled.
https://github.com/mthom/scryer-prolog/issues/2228
and
https://github.com/mthom/scryer-prolog/issues/2206
> Fix backslash docs

- src/lib/si.pl
- src/lib/when.pl
- src/tests/when.pl
- tests/scryer/cli/src_tests/when_tests.stdout
- tests/scryer/cli/src_tests/when_tests.toml
As my latest foray into attributed variables and constraints[^1], here is an implementation of `when/2` with `when_si/2` as a bonus[^2]. It was unexpectedly easy to implement, and I think I'm starting to see a pattern in all of those constraints I'm implementing, but I will talk about this in a discussion in another time. I'm pretty sure it's correct, but I will be making automated tests for it later. Can you think of any tricky cases where it may break? Also, this is probably not very optimized.
Closes #711.
[^1]: Is `when/2` a constraint?
[^2]: Is there really any use for `when_si/2` apart for making test cases for `when/2`?
> Add when/2 and when_si/2

- src/parser/parser.rs
```prolog
?- [user].
test1([a,b,_]).
test2([a,b,c,_,d,e,f,_]).
?- wam_instructions(test1/1, Ins), maplist(portray_clause, Ins).
% The list is parsed as a partial string starting with "ab".
get_partial_string(level(shallow),"ab",x(1),true).
unify_variable(x(2)).
get_list(level(deep),x(2)).
unify_void(1).
unify_constant([]).
proceed.
...
?- wam_instructions(test2/1, Ins), maplist(portray_clause, Ins).
% The list is parsed as a partial string starting with "abc".
get_partial_string(level(shallow),"abc",x(1),true).
unify_variable(x(2)).
get_list(level(deep),x(2)).
unify_void(1).
unify_variable(x(2)).
% Inside the tail of the first partial string there is another partial string
% starting with "def".
get_partial_string(level(deep),"def",x(2),true).
unify_variable(x(3)). …
```
> Parse as much of a list as possible as a partial string 

- Cargo.lock
- Cargo.toml
This was done in Alpine Linux in order to build Scryer in RISC-V (https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/scryer-prolog/ring-0.17.5.patch?ref_type=heads)
> Update ring and bump versions in Cargo.lock

- src/lib/clpz.pl
This allows subsequently invoked constraints to take the entire filtering results into account, instead of being invoked when the obtained information is not yet entirely used.
It speeds up programs such as the one in https://github.com/triska/clpz/issues/26
> ENHANCED: Suspend propagation during filtering in scalar product constraints.

- src/loader.pl
- src/machine/compile.rs
- src/machine/mod.rs
- src/read.rs
- src/toplevel.pl
- tests/scryer/cli/issues/singleton_warning.stdout
Following the discussion at #2253, this makes warnings be emitted as Prolog comments, meaning that they can be read back as valid Prolog. Example:
```prolog
?- [user].                                                                                                                                                                                         
test :- X = _.                                                                                                                                                                                     
% Warning: singleton variables X at line 1 of user
```
> Emit warnings as Prolog comments

- build/instructions_template.rs
- src/bin/scryer-prolog.rs
- src/lib/os.pl
- src/loader.pl
- src/machine/dispatch.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
- src/toplevel.pl
By moving `argv/1` to `library(os)`, this predicate can be found and documented just like any other predicate. In addition, special code to handle the arguments in the top-level has been simplified.
> Move argv/1 to library(os)

- src/lib/clpz.pl
Example:
?- X #>= Y.
%@    clpz:(X#>=Y).
> Correct arithmetic disequalities accidentally broken in f5d9a67f3688ec9bb08dd3add05614552e082555

- src/lib/clpz.pl
The only solutions for `Z #= X^Z` are `X = Z, X in -1\/1`. Also helps avoid big numbers.
> Special case for `(^)/2`

- src/arena.rs
- src/atom_table.rs
- src/heap_iter.rs
- src/heap_print.rs
- src/machine/arithmetic_ops.rs
- src/machine/copier.rs
- src/machine/gc.rs
- src/machine/lib_machine.rs
- src/machine/mock_wam.rs
- src/machine/partial_string.rs
- src/machine/stack.rs
- src/machine/streams.rs
- src/parser/char_reader.rs
- src/raw_block.rs
- tests/scryer/issues.rs
- tests/scryer/main.rs
- tests/scryer/src_tests.rs
Scryer has a lot of unsafe code, so running it through Miri to find UB (Undefined Behavior) is very obvious. Running the actual program is blocked on _at least_ (there may be more requirements) Miri implementing `pipe2`. I ignored enough tests so that `cargo miri test` can actually run without errors, and fixed some pointer-integer-pointer casts so that it runs with no warnings and more accurate errors. I documented in each ignored test more or less where the UB blocking it was found.
It seems that the most important UB is in `streams.rs`, as it blocks most tests. Solving these issues is really important, because with UB in the code even if it works fine _now_ it can change behavior when changing compiler versions and completely break everything with very subtle and elusive bugs. However, …
> Initial Miri support

- src/lib/dcgs.pl
These non-terminals take a grammar rule body and additional arguments as arguments. These arguments are appended to the first argument.
A key motivation for the introduction of these non-terminals is found in the discussion and sample code provided by @bakaq in: https://github.com/mthom/scryer-prolog/discussions/2260
In this way, portable higher-order DCG programming is possible while keeping the logical grammar rule expansion implementation dependent.
Example:
?- phrase(phrase('.', a, []), Cs).
Cs = "a".
> ADDED: Support for higher-order non-terminals phrase//[2,3]

- src/lib/clpz.pl
- src/lib/dcgs.pl
This addresses #2285.
Also, `(->)//2` is now only supported in the context of if-then-else, i.e., as `( If -> Then ; Else )`, but not as a standalone construct, and also not in the context of&nbsp;`|`.
> Throw representation errors for unsupported DCG grammar control constructs

- src/lib/clpz.pl
This was suggested and contributed by @librarianmage in: https://github.com/mthom/scryer-prolog/issues/2225#issuecomment-1890801923
Many thanks!
If anyone can find a better predicate name, please let us know any time!
> ADDED: clpz_t/2, generalizing support for use with library(reif)

- src/lib/charsio.pl
Surrogate pairs form a gap in valid character codes, see:
https://github.com/mthom/scryer-prolog/issues/2326#issuecomment-1937864665
Many thanks to @Skgland for the pointer, and to @librarianmage for the question that spawned this!
This addresses #2326.
> FIXED: char_type/2 for unbound first argument.

- INDEX.dj
Since the release files are not available here: https://github.com/mthom/scryer-prolog/releases/tag/v0.9.4 and directly linking to the action's output is not recommended (the build files will get deleted eventually), I've uploaded the binaries to an Azure Storage as a temporary measure.
Sorry for the delay :(
> Website: link release v0.9.4

- src/lib/crypto.pl
In addition, the ability to use a list of bytes when the `encoding(octet)` option is used is now no longer documented because it is considered deprecated and a candidate for removal in the future. Use strings instead in your applications for greater efficiency and type consistency.
> Documentation improvements for encoding(octet) option in several predicates

- src/lib/format.pl
This is ready for testing. Enjoy!
This change alone already makes the example from #2360 more than twice as fast:
<pre>
<b>?- I is 2^2^8,
time((exp(12),phrase(format_("~16r", [I]), _),false)).</b>
% CPU time: 0.844s, 3_944_468 inferences
false.
</pre>
<s>Before merging this, #2361 should be resolved or at least confirmed, and any unnecessary module qualifications should then be removed if possible.</s>
**Update**: #2361 is now nicely resolved, I have removed the module qualifications which are now unnecessary.
> ENHANCED: Partial evaluation of format_//2 and related constructs

- .github/workflows/ci.yml
- Cargo.toml
- src/arena.rs
- src/machine/machine_indices.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
- src/parser/char_reader.rs
The use of unsafe Rust is revised in arena.rs to answer some of the criticisms made in #2391, particularly regarding the misaligned allocation of some stream types. Explicit use of `alloc` is removed in favor of `Box`. `TypedAllocSlab<Payload>` is a type parameterized template over `AllocSlab` used to allow rustc to get value allocation right. As well, some new macros (like `mem::offset_of!`) are used to calculate byte offsets into structs. This requires bumping the Rust version in Cargo.toml to 1.77.
> Improve use of unsafe Rust in arena.rs (#2391)

- .github/workflows/ci.yml
- src/machine/streams.rs
- src/parser/parser.rs
was removed in #2393 instead of being updated, see
- https://github.com/mthom/scryer-prolog/pull/2393#discussion_r1585963855 and
- https://github.com/mthom/scryer-prolog/commit/79bc2d9c68da2257a94eb22ef8717a304173e344#commitcomment-141790142
> re-add CI job to test Cargo.toml rust-version

- src/lib/time.pl
This is needed for benchmarking library(reif) and its newly provided goal expansion (#2433).
It partly addresses #321.
> ADDED: Preliminary support for statistics/2.

- src/http.rs
- src/machine/streams.rs
- src/machine/system_calls.rs
Implements `position_relative_to_end` to HttpRead so we can know when the transmission has finished. It fixes: https://github.com/mthom/scryer-prolog/discussions/2437
> Fix at_end_of_stream/1 for http read stream

- Cargo.toml
- build/main.rs
- src/http.rs
- src/machine/mod.rs
- src/machine/streams.rs
Instead of "copy-paste-ing" the content of the prolog libraries into the generated `libraries.rs` file,
construct a path relative to the generated file to the prolog library file and use `include_str!` to include it.
This means instead of generating a file like (notice the horizontal scroll bar)
<details>
<summary>Old generated file ~882kb</summary>
```rust
use indexmap::IndexMap;
const LIB_ARITHMETIC: &str = "/** Arithmetic predicates\n\nThese predicates are additions to standard the arithmetic functions provided by `is/2`.\n*/\n\n:- module(arithmetic, [expmod/4, lcm/3, lsb/2, msb/2, number_to_rational/2,\n                       number_to_rational/3, popcount/2,\n                       rational_numerator_denominator/3]).\n\n:- use_module(library(charsio), [write_term_to_chars/3]).\n:- …
```
> simplify generated libraries map by using `include_str!`

- src/arena.rs
- src/machine/loader.rs
- under some circumstances the payload is accessed durring reset which would cause a segfault if we drop the payload too early
> fix segfault by dropping loader state payload after resetting machine

- .envrc
- .gitignore
- flake.lock
- flake.nix
This should make the lives of people using Nix/NixOS (like me) much easier. This will also enable anyone with the nix package manager to run (or even install) the latest git version directly from Github like this:
```
$ nix run github:mthom/scryer-prolog
```
Which I think is a nice accessibility option for more users to test the latest master. Maybe we should put this in the README? 
Included are 2 devshells, one with an stable toolchain and one with nightly (with Miri included). A `.envrc` is also provided to automatically load the stable devshell environment with [direnv](https://direnv.net/) when entering the directory.
There is also support for nix in MacOS, and I think I would need to change this a bit to make it work there, but I don't have a Mac to test it. We also _could_ go full …
> Add flake.nix

- src/arena.rs
- src/ffi.rs
- src/machine/stack.rs
- src/raw_block.rs
Running the command from #2449 
<details><summary>Details</summary>
<p>
made more readable for use as a script file rather than a CLI one-liner
```bash
L=10000
while : ; do 
echo $L
sh -c "ulimit -v $L;~/home/git/scryer-prolog/target/release/scryer-prolog -f -g halt"
L=`expr $L + 10000`
done
```
</p>
</details> 
now result in 
<details><summary>Details</summary>
<p>
```bash
$ >bash ./test.sh 
10000
/home/bennet/git/scryer-prolog/target/release/scryer-prolog: error while loading shared libraries: libssl.so.3: failed to map segment from shared object
20000
thread 'main' panicked at /home/bennet/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ctrlc-3.4.4/src/lib.rs:150:10:
failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
note: run …
```
> Fix looping memory allocation

- benches/setup.rs
- src/machine/lib_machine.rs
- src/machine/parsed_results.rs
This improves the parsing of terms in `lib_machine`. The current interface can't differentiate strings, variables and atoms, just crashes on composite terms, and is very brittle as it's implemented as parsing a string (that isn't even in canonical form, so operators). With this PR it now does a direct heap walk to parse the term. Here's an test demonstrating what it can represent:
```rust
let mut machine = Machine::new_lib();
let query = "X = a(\"asdf\", [42, 3.14, asdf, a, [a,b|_], Z]).".into();
let result = machine.run_query(query);
let expected = Value::Structure(
// Composite term
"a".into(),
vec![
Value::String("asdf".into()), // String
Value::List(vec![
Value::Integer(42.into()),  // Fixnum
Value::Float(3.14.into()),  // Float
Value::Atom("asdf".into()), // Atom …
```
> Value heap walk in lib_machine

- Cargo.toml
`0.11.*` instead of `0.11.27`.
Cargo will pick the latest patch that's possible with `*`, but also not fail if another dependency in the build ensemble has reqwest pinned to something below patch 27.
This enables us to include scryer alongside an older Deno version that we're currently forced to stick with.
> Relax version constraint on reqwest dependency 

- src/lib/error.pl
This just converts the documentation that was already there to Doclog format so that it will appear [here](https://www.scryer.pl/error).
`library(queues)` and `library(tls)` also have docs already that aren't in the Doclog format, and I was going to convert them all in a single PR, but at least for `library(queue)` I realized that it wasn't going to be as simple as `library(error)` because of the predicate signatures that I don't really understand.
> Convert library(error) docs to Doclog format

- src/lib/iso_ext.pl
- src/lib/ops_and_meta_predicates.pl
While reading loader.pl module it was not obvious to me at all what exactly does `non_counted_backtracking` to the predicates and should I use it for new predicates in that module or not. After reading sources I came up with new documentation. Basically there is a single counter which is incremented on every instruction that is an "inference", but for "default" instructions (instructions that start with `default_` prefix) that counter isn't incremented and isn't checked. When counter reaches a limit (defined for example when you use `call_with_inference_limit/3`) it forces unconditional exit and stops evaluating rest of instructions (I hope I got that part right).
**UPDT:**
There is only a single inference counter and a single variable that holds a max inference limit, that's why when you …
> Document non counted backtracking

- src/machine/system_calls.rs
On current `master`, if we compile without the `hostname` feature there is a compiler error (unless the target is Wasm). This fixes it. In particular, this allows compiling Scryer Prolog with `--no-default-features`.
> Fix not compiling without hostname feature

- src/loader.pl
- src/toplevel.pl
I went and reimplemented a good part of the toplevel on top of a predicate I called `run_query_goal/4`. It passes all the current tests, and works the same as the old implementation in my manual testing. The idea is to eventually make this same predicate drive the library interface (when I figure out how to call arbitrary Prolog from the Rust side[^1]), other (pseudo) toplevels, and maybe even some other kinds of things, it's very general. It takes 4 arguments: the query term, a list of variable names (in the form given by the `variable_names(-VarNames)` option of [`read_term/3`](https://www.scryer.pl/builtins.html#read_term/3)), a callback goal expecting 3 arguments and a list of options. This predicate then runs the query and calls the callback with the leaf answer and additional …
> Toplevel reimplementation with leaf answer callbacks

- src/toplevel.pl
I ran into the same problem today and I figured I'd take a stab at it. Unfortunately, I'm not certain it is the right approach, but it no longer errors like it did before.
Fixes #2650.
> toplevel.pl: fix arity mismatch in read_input/2

- src/lib/builtins.pl
> s/red/read/ typo in documentation.

- src/machine/system_calls.rs
Windows sends `KeyEventKind::Release` events, and Linux does not. This resulted in a release of `\n` being interpreted as a `\n` on Windows and preventing the user from getting more than one answer at the toplevel.
Closes #2672
> Ignore `KeyEventKind::Release` events when reading a char

- src/lib/builtins.pl
Mirrored the wording in the docstrings for `read/1` and `read_term/3`.
> Documentation for read/2

- src/lib/clpb.pl
Many thanks to @hurufu for the very nice definition!
This is until library(random) provides this functionality, and a good name is found for it. See #2670.
> introduce and use weighted_maybe/2

- build/main.rs
- src/toplevel.pl
In order to support hermetic build tools like bazel, I had to resolve the lib path when compiling the libraries.rs instead of baking the absolute path from the build/main.rs file. Bazel will create a temporary sandbox to compile and execute the build script and a different sandbox to compile the resulting code.
Bonus (should be a separate PR):
The function `Machine::run_module_predicate` is now private to the crate so we can't do the following anymore:
1. Create a custom Machine
2. Load additional modules
3. Run the repl on the pre-configured machine.
So by exporting the repl atom, we can replace this code in 0.9.4
```
let mut wam = Machine::new(MachineConfig::default());
wam.load_module_string("customlib", include_str!("customlib.pl").to_string()); …
```
> Support hermetic build environment

- src/lib/assoc.pl
It seems DocLog can't handle a double space in the `%%` line of documentation. You can see in https://scryer.pl/assoc that `max_assoc` appears twice. First time documented and second time undocumented:
> Ensure max_assoc/3 is shown as documented

- src/lib/format.pl
This addresses #2713. Many thanks to @notoria for reporting this excellent case!
Example:
?- portray_clause(A = @).
A= @ .
true.
At other positions the now inserted space is unnecessary, as in:
?- portray_clause((head:- @,b)).
head :-
@ ,
b.
true.
The toplevel has a similar issue:
?- C = # ; false.
C = # |<-- cursor is here; redundant space after #
There may be a way to solve this issue for all cases like this.
> prevent accidental amalgamation of graphic token chars in output

- src/lib/dcgs.pl
- tests/scryer/cli/issues/not_supported_dcg_constructs.in/main.pl
- tests/scryer/cli/issues/not_supported_dcg_constructs.stdout
- tests/scryer/cli/issues/not_supported_dcg_constructs.toml
Some DCG constructs aren't supported and can't be expanded, here we remove offending DCG rule and don't compile it at all – in a similar fashion to what we do when incorrect goal was found – whole predicate isn't getting compiled.
Fixes #2675
I know that request has low priority, but it is so much simpler than loder.pl refactoring, so I just couldn't help myself and fixed it right away.
> Remove DCGs that have thrown an exception during term expansion

- src/lib/files.pl
"returns" is not used in this way in logic programming. "return" suggests that something went away and is now coming back, but this is never the case in these situations. The arguments may be variables or also fully known at the time of the call in most cases.
> state when the predicates are true

- src/lib/clpb.pl
This reverts commit e185b626bdf1a99ab8188ae39875f645c0de90f0.
This change is now no longer needed, and the underlying issue is apparently somewhere else entirely. See the description at&nbsp;https://github.com/mthom/scryer-prolog/issues/2732
Current master behaves differently from Scryer as it was at 099d9aaca6509496ccb28c522659b990f42037f0 (i.e., preceding the commit that is now being reverted), even on the same file.
For an example, see: https://github.com/triska/scryer-prolog/commit/dd41176b97d8369c3bb7de1c9932a9c3d10a0466
Scryer now works as expected, and compatibly with SICStus. We still need to find out what fixed the root cause of this issue.
> Revert "FIXED: CLP(B): Delay BDD restriction until after the instantiation"

- src/heap_iter.rs
- src/machine/heap.rs
This fixes two sources of undefined behavior:
- `Heap::drop()` could be called while `InnerHeap::ptr` is null, but it did not account for it, causing it to attempt to free a null pointer.
- `ReservedHeapSection::push_pstr_segment()` and `Heap::copy_str_within()` were using `ptr::align_of` to compute the number of bytes needed to pad the string with zeroes, but since the underlying buffer (`InnerHeap::ptr`) itself isn't aligned to `size_of::<HeapCellValue>()`, the returned values would vary randomly between 0 and 3, sometimes causing those two functions to not mark the cells as allocated.
That second one took me a few hours to track down, since the tests would randomly work again should the stars (literally) align ^^'
> rebis-dev: Fix UB detected by miri in tests

- src/machine/dispatch.rs
- tests-pl/load-context-unreachable.pl
- tests/scryer/issues.rs
Loading a file with the following triggers a panic, caused by `Machine::load_context_module` calling `Machine::unify_atom` with un-derefed `Var`s:
```prolog
:- initialization((M = user, loader:load_context(M))).
```
This changes the code in `dispatch.rs` to first dereference the register before calling `load_context_module`.
> Fix load_context_module triggering unreachable!()

- flake.nix
Hello! I was delighted to see my development environment automatically set itself up due to the work done in https://github.com/mthom/scryer-prolog/pull/2482, and then slightly less delighted when I saw a failure to compile due to the `SystemConfiguration` framework not being provided as Rust expects on macOS.
Following the suggestion at https://discourse.nixos.org/t/ld-framework-not-found-system/15096/7, I added this framework to `buildInputs` when evaluating the flake for macOS, and now Scryer happily compiles with a single `cargo build --release`.
> fix: compile under Nix flake on macOS

- src/lib/builtins.pl
- src/loader.pl
- src/machine/system_calls.rs
- src/tests/module_resolution.pl
- tests-pl/issue2725.pl
- tests/scryer/cli/src_tests/module_resolution.stdout
- tests/scryer/cli/src_tests/module_resolution.toml
- tests/scryer/issues.rs
Fixes #2725.
`phrase(GRBody, _, _)` first calls `strip_module(GRBody, M, _)` to split `GRBody` into the module and the predicate, but then calls `call(M:GRBody3)` to prepend the module again.
However, when there is no module, then `strip_module` doesn't assign a value to `M`.
~~I first tried to fix this by making it so that `strip_module(predicate, M, Pred)` assigns `[]` to `M`, but that seems to have broken several pieces of code that instead check whether or not `M` was assigned.~~
~~Right now I have defaulted to just handle the result of `strip_module` in `phrase` instead, but I feel like it would be much cleaner to allow `strip_module` to assign a value to `M` and to work both ways. `call` could then seamlessly work with it.~~
~~As per the suggestions of Markus, `strip_module/3` now …
> Fix dcgs using call(M:Pred) when M was left unassigned

- src/machine/dispatch.rs
- tests/scryer/cli/issues/compilation_bug.in/a.pl
- tests/scryer/cli/issues/compilation_bug.in/b.pl
- tests/scryer/cli/issues/compilation_bug.in/c.pl
- tests/scryer/cli/issues/compilation_bug.stdin
- tests/scryer/cli/issues/compilation_bug.stdout
- tests/scryer/cli/issues/compilation_bug.toml
This fixes a bug in the current attributed variables implementation that creates a lot of strange bugs that seem like miscompilations.
Closes #2706, closes #2809, closes #2632.
> Fix bug in finding arity for verify attributes

- src/loader.pl
- tests/scryer/cli/src_tests/directive_errors.md
- tests/scryer/main.rs
A quick (partial) fix the the singleton warning line number. See what you think!
Bumps the line number for the singleton warning. When the singleton occurs on the same line at the term starts, the line number is correct (e.g.line 1 instead of 0):
foo(X).
However it stills mis-reports this line number as 1 instead of 5:
foo(1) :-
true,
true,
true,
Y.
See issue #1356.
> Line numbers start at 1

- README.md
Also fix the outdated rust toolchain version listed,
either referring to the version specified in Cargo.toml or for the latest crates.io release include a shilds.io badge.
cc mthom/scryer-prolog#2781, mthom/scryer-prolog#2784
> Expand the build/install section of the readme

- src/arena.rs
- src/machine/config.rs
- src/machine/lib_machine/mod.rs
- src/machine/lib_machine/tests.rs
- src/machine/streams.rs
- src/macros.rs
This adds a new `StreamConfig` option that allows both to asynchronously react to the `Machine` writing to stdout or stderr, and to programatically send data to its stdin, all in-memory.
This is an incredible feature for many reasons, like being able to get stdout in parts and not just all at once, but the application I have in mind is running the same toplevel we use for CLI inside Wasm in the Scryer Playground, which will be a great improvement in usability!
> Callback streams for use as library

- src/machine/lib_machine/mod.rs
- src/machine/mod.rs
- src/toplevel.pl
Fixes #2815, see that issue for my investigation.
This is a one-line fix that I'm quite proud of :)
----
If the topmost query for `run_module_predicate` needs to backtrack, then before this commit, one of the following two things may happen:
- A dangling OrFrame is read at stack offset 0
- An AndFrame was at stack offset 0 would be read as an OrFrame
This can be seen by either calling `run_module_predicate` with a throwing predicate (encountering the second scenario) or a failing predicate (encountering the first scenario), or by running the following in the REPL, which triggers a `throw/1` within the error handler, propagating it all the way up (and encountering the second scenario):
```prolog
?- current_output(S), open(stream(S), write, S0, [type(binary)]).
```
Currently, `Stack` is not …
> Fix backtracking on the topmost predicate triggering UB in run_module_predicate

- Cargo.lock
- Cargo.toml
- flake.nix
- src/bin/scryer-prolog.rs
- src/lib.rs
- src/wasm.rs
This reworks the Wasm API to match the Rust API and therefore be much more flexible (query iterators allowing continuous feedback and infinite leaf answers, actual term data representation instead of just strings, etc...). This was some of the trickiest Rust code I've ever wrote (self-referential structs, single threaded channels, etc...), but I managed to do all of it without using unsafe. If anyone has suggestions on how to do it better please tell me. If anyone has suggestions on how to make the interface more idiomatic for Javascript I would also like to hear it!
This is still very rough and needs polish (and documentation, which I intentionally deferred), but already works really well as is.
Non-goals for this PR:
- Have a way to capture stdout like the removed `eval_code`, and some …
> Wasm rework

- src/lib/format.pl
This addresses #2790.
The issue first appeared in an example reported by @ak-1 in #2788, and was successfully analyzed by @flexoron. Many thanks!
> FIXED: instantiation and type check for string arguments

- src/machine/system_calls.rs
- tests-pl/issue-http_open-hanging.pl
- tests/scryer/helper.rs
- tests/scryer/issues.rs
Hello 👋🏼,
Replacing `futures::executor::block_on` with `tokio::block_in_place` may help in closing https://github.com/mthom/scryer-prolog/issues/2834:
CI workflows appears to be ok in this [fork](https://github.com/thierrymarianne/contrib-scryer-prolog/actions/runs/13529411529/job/37807772388).
Please, let me know how a better fix could be applied 
(for the time being or in the long run).
> Prevent http_open/3 from hanging

- src/functor_macro.rs
- src/machine/heap.rs
This solves a very old issue that was for years misattributed to the implementation of compact partial strings. It was in fact just a parsing problem, which means that no matter how good the implementation of partial strings was, this would still be a problem.
This closes #1969 and #2810. I think it also closes #2757 if I understood what it means correctly and maybe even #2554 (at least the internal representation part, the printing is still a bit lacking).
```prolog
?- use_module(library(lists)), length("\x0\\x0\", N). % issue 1969 
N = 2.
?- A = "hello \x00\world". % issue 2810
A = "hello \x0\world".
?- A = "\x0\a". % issue 2757
A = "\x0\a".
?- write("1\x0\2"), nl. % issue 2554
[1,,2] % Doesn't actually print \x0\, but at least there's clearly 3 elements.
true.
?- writeq("1\x0\2"), nl. …
```
> Fix parsing of \x0\ in partial strings

- src/lib/clpz.pl
Trivial change but this prevents the HTML output from being erroneously italicized.
----
Previously it looked like
> Use backticks when referencing predicate in docs.

- src/lib/format.pl
In particular, variables now start with "_".
Example:
?- format("~w", [X]).
%@ _A   true.
Found thanks to a discussion initiated by @haijinSk: https://github.com/mthom/scryer-prolog/discussions/2863
> ENHANCED: format specifier ~w more faithfully emulates write/1

- src/lib/charsio.pl
This addresses part of #2871, raised by @haijinSk. Many thanks!
> generalize read_from_chars/2 and read_term_from_chars/3 to allow instantiated Term

- src/wasm.rs
This PR makes [`WasmQueryState`](https://github.com/mthom/scryer-prolog/blob/8558bd22142220c4de4992dc0f4b3f46502b42d8/src/wasm.rs#L113) an [Iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators#iterables), enabling the use of the `for...of` construct in JavaScript to iterate over query results.
I explored the possibility of achieving this using `js_sys::Reflect::set`, but was unable to define a function that could be correctly bound to JavaScript and return the appropriate `this` context from a `WasmQueryState` instance.
Related to #2873
> Make `WasmQueryState` Iterable in JavaScript

- Cargo.lock
- Cargo.toml
Pulls in latest `libffi` and `libffi-sys` dependencies to fix a compilation error on aarch64 macOS builds.
> Update `libffi` and `libffi-sys` dependencies to fix aarch64 macOS build

- .github/workflows/ci.yml
- Cargo.toml
- flake.lock
Let's get this over with.
This bumps the Minimum Supported Rust Version from 1.77 to 1.85, the Rust version officially supported in Debian Trixie. It also bumps flake.lock because Rust there was pinned to a version older than that. This gives us access to strict provenance (#2019), Rust 2024 edition if we want, and also eliminates (at least temporarily) the whole annoyance of making sure the build and all dependencies work with a version of Rust that is almost a year old at this point.
This also fixes CI on master, which currently fails just because of 1.77.
> Bump MSRV and update flake.lock

- src/lib/iso_ext.pl
- src/machine/system_calls.rs
As a consequence, resulting strings are now quickly reclaimed on backtracking.
This addresses #2912.
Test case:
:- use_module(library(iso_ext)).
:- use_module(library(lists)).
ab(a).
ab(b).
Sample query:
?- length(Ls, 1_000_000),
maplist(ab, Ls),
partial_string(Ls, Es0, []),
Es0 == Ls.
Ls = "aaaaaaaaaaaaaaaaaaa ...", Es0 = "aaaaaaaaaaaaaaaaaaa ..."
;  Ls = "aaaaaaaaaaaaaaaaaaa ...", Es0 = "aaaaaaaaaaaaaaaaaaa ..."
;  Ls = "aaaaaaaaaaaaaaaaaaa ...", Es0 = "aaaaaaaaaaaaaaaaaaa ..."
;  Ls = "aaaaaaaaaaaaaaaaaaa ...", Es0 = "aaaaaaaaaaaaaaaaaaa ..."
;  Ls = "aaaaaaaaaaaaaaaaaaa ...", Es0 = "aaaaaaaaaaaaaaaaaaa ..."
;  ... .
running in constant memory.
> ENHANCED: partial_string/3 no longer creates atoms

- src/arena.rs
- src/atom_table.rs
- src/ffi.rs
- src/functor_macro.rs
- src/heap_print.rs
- src/machine/heap.rs
- src/machine/lib_machine/mod.rs
- src/machine/stack.rs
- src/machine/system_calls.rs
- src/macros.rs
- src/offset_table.rs
- src/raw_block.rs
- src/types.rs
Now that MSRV is 1.85 and we have access to it, this migrates completely from integer-pointer casts to strict provenance, or to exposed provenance where it wasn't sufficient. This already makes Miri go deeper, but it still can't really help a lot after `with_exposed_provenance` is called. At least now we have easily greppable problem spots in the code to eventually get to full strict provenance (any place with `expose_provenance` and `with_exposed_provenance`). I've added comments explaining the trickier spots where exposed provenance is needed (mostly the stack).
In theory if there are no `with_exposed_provenance` calls in the code, then there isn't a need for any `expose_provenance` either, so these spots should be the focus going forward.
The flaky tests pass Miri without even any …
> Migrate to strict and exposed provenance

- src/machine/machine_state_impl.rs
The fact that such a mistake in macro usage is even possible could be a sign that the macro definition should be stricter.
> address #2924, reported by @haijinSk. Thank you a lot!

- src/machine/machine_state_impl.rs
This addresses another aspect of #2924, found by @haijinSk. Thank you again!
Example:
?- "aaaaaaa" = [_,_,_,_,_,_|T], arg(2, T, 2).
> FIXED: correct partial string tail calculation in arg/3

- src/machine/heap.rs
This seems to fix the flaky tests. `pstr_sentinel_length` expected the length of the string but it was being passed an address. When the address was aligned to 8 (which is quite common in this case actually, especially in 64 bit targets) the result was as expected, but the pointer from which we get the address has alignment of 1, so this is actually non-deterministic!!!
While this wasn't UB, I still want to shout out Miri for making it easier to reproduce this.
> Fix flaky tests (Part 1)

- src/arena.rs
- src/arithmetic.rs
- src/forms.rs
- src/functor_macro.rs
- src/heap_print.rs
- src/indexing.rs
- src/machine/arithmetic_ops.rs
- src/machine/attributed_variables.rs
- src/machine/dispatch.rs
- src/machine/loader.rs
- src/machine/machine_state.rs
- src/machine/machine_state_impl.rs
- src/machine/mod.rs
- src/machine/system_calls.rs
- src/macros.rs
- src/parser/ast.rs
- src/parser/lexer.rs
- src/parser/parser.rs
- src/types.rs
`Fixnum::build_with` was silently truncating out-of-bounds values,
this is now `Fixnum::build_with_unchecked` and `Fixnum::build_with` can only be called with types that are guaranteed valid. This also adds a fallible `Fixnum::build_with_checked` that can be called with types that may be out-of-bounds.
Further this replaces the `call_as_fixnum!` macro with an unsafe function  `HeapCellValue::to_fixnum_or_cut_point_unchecked` (didn't know which should be which so one function for both ).
The added unsafe functions contain `debug_asserts!` so that tests and debug builds should panic if an invalid value is passed to them, instead of silently corrupting the machine state.
This was originally b133ef563bfb47cbc800a60ad8f86c705ad75533 part of #2786
> make it easier to use Fixnum correctly

- src/lib/ops_and_meta_predicates.pl
- src/tests/arithmetic.pl
`xor` is not an ISO infix operator
> Remove xor as a builtin infix operator

- Cargo.toml
- src/machine/mod.rs
This code was introduced in #2457 to use `LazyLock`, introduced in Rust 1.80. The targeted Rust version was 1.77 in Cargo.toml. Now that Cargo.toml lists the minimum version as 1.85, this compilation flag is no longer necessary.
> Remove obsolete compatibility for Rust<1.80

- .github/workflows/ci.yml
Even if `fmt` fails, there can be useful deeper insights from clippy.
> CI: run clippy even if fmt fails

- src/lib/when.pl
It seems like `when/2` can accept an arbitrary goal as a condition. This documents what is expected for that argument.
> Document `when/2` Condition

- src/loader.pl
This lets us embed toplevel interactions in Prolog programs. Embedded toplevel interactions are currently ignored.
Example:
:- use_module(library(lists)).
?- member(X, "abc").
X = a
;  X = b
;  X = c.
> preliminary support for a subset of quads introduced by @UWN

- src/lib/error.pl
A good example of call_with_error_context/2 was recently provided by @Skgland in d907f86c8d3bf5b5429c9f53187b65473fcbfce0. Many thanks!
> ADDED: variants of errors promoting call_with_error_context/2

- .github/workflows/ci.yml
- also adjust the `Zip binaries for release` and `Release` jobs to match current matrix configuration
> use cargo-deb in CI to build debian deb packages

- src/machine/system_calls.rs
- src/read.rs
See issue #3057 and #2787 for a description of the problem.
This patch makes some builtins read input without using the readline functionality (tab-completion for example).
I am not 100% sure this is the correct thing to do though, so if somebody more involved in the project could give their opinion, that would be nice.
> Don't use "readline" input functionality for certain builtins
