README.md
It's not much, but I found it useful to see at a glance what's done or not.
=> README: Use checkboxes to track item completion in Phase 2

README.md
The sample interactions now use the new toplevel conventions.
=> update toplevel interaction

src/prolog/lib/format.pl
This commit adds a few more features to `format_//2`, and also improves correctness, error handling and determinism.
=> ENHANCED: format_//2 now supports ~a, ~d, ~Nd, ~D, ~ND, ~Nn, ~i and ~*

src/prolog/examples/least_time.pl
=> examples/least_time.pl: fix typo

src/prolog/lib/format.pl
At the moment, `library(format)` seems to be a fitting place.
In the eventual library organization, `portray_clause/1` and
related predicates may be moved to their own dedicated library.
=> ADDED: provide a rudimentary version of portray_clause/1

src/main.rs
Fixes #339.
At least I hope so. I didn't come up with an idea how to test this with
little effort.
=> main: fix version reporting without git

README.md
=> update the toplevel description, incorporating the latest changes

src/prolog/lib/charsio.pl, src/prolog/lib/format.pl
=> Documentation addition, and correction of error term

src/prolog/lib/format.pl
Example:
?- portray_clause((A :- B)).
%@ A :-
%@    B.
%@    true
%@ ;  ...
Also, change the indentation from 8 to 3 at the express request of @UWN.
=> portray_clause/1 now correctly tracks variable names (#376)

src/main.rs, src/prolog/clause_types.rs, src/prolog/machine/system_calls.rs, src/prolog/toplevel.pl
Reverts mthom/scryer-prolog#419
=> Revert "Enhanced command line"

src/prolog/lib/crypto.pl
Sample use case:
Prolog implementation of the the Poly1305 message-authentication code.
https://www.metalevel.at/prolog/poly1305aes.pl
=> ADDED: Initial version of library(crypto).

README.md, src/prolog/clause_types.rs, src/prolog/lib/crypto.pl, src/prolog/machine/system_calls.rs
=> ADDED: crypto_data_hash/3, computing cryptographically secure digests

Cargo.toml, src/prolog/lib/crypto.pl, src/prolog/machine/system_calls.rs
This is used for example for Bitcoin address generation.
Please review, and merge if applicable. There may be a way to write this more compactly, please have a look. Thank you!
=> ADDED: ripemd160 digest algorithm

src/prolog/lib/crypto.pl, src/prolog/machine/system_calls.rs
This also addresses #523.
Many thanks to @notoria for the test case.
=> Add type checks to increase robustness of library(crypto)

src/prolog/clause_types.rs, src/prolog/lib/pio.pl, src/prolog/machine/system_calls.rs
This allows us to specify type(binary), and read from binary files with DCGs.
=> ADDED: phrase_from_file/3 in library(pio)

src/prolog/lib/pio.pl
=> import member/2 from library(lists)

src/prolog/clause_types.rs, src/prolog/lib/builtins.pl, src/prolog/machine/system_calls.rs
=> ADDED: halt/1, halting with specified exit code

src/prolog/examples/utf8.pl, src/prolog/lib/charsio.pl
=> Add decoding of UTF-8 sequences

README.md
I have split this into its own pull request to make it easier to review and apply.
=> explain .scryerrc configuration file

README.md, src/lib/format.pl
I have split this into its own pull request to make it easier to review and apply.
=> ADDED: portray_clause/2, writing to a specified stream.

README.md, src/lib/http/http_open.pl, src/lib/sgml.pl, src/lib/xpath.pl
For example, is anyone interested in the chapters of *The Power of Prolog*?
Here we go:
<pre>
?- http_open("https://www.metalevel.at/prolog", S, []),
load_html(stream(S), DOM, []),
<b>xpath(DOM, //li(text), Chapter),</b>
portray_clause(Chapter),
false.
</pre>
Yielding:
<pre>
"Introduction".
"Facets of Prolog".
"Logical Foundations".
"Basic Concepts".
"Data Structures".
etc.
</pre>
Enjoy!
=> ADDED: library(xpath) for convenient analysis of HTML and XML documents.

Cargo.toml, README.md, src/clause_types.rs, src/lib/sgml.pl, src/lib/xpath.pl, src/machine/system_calls.rs
=> ADDED: load_xml/3 to load XML files from streams, files and strings.

README.md, src/lib/csv.pl
add csv library for scryer-prolog
=> add csv library

README.md, src/clause_types.rs, src/lib/error.pl, src/lib/files.pl, src/lib/os.pl, src/machine/system_calls.rs
Together with `library(files)`, this addresses #511.
=> ADDED: library(os), reasoning about environment variables.

src/clause_types.rs, src/lib/files.pl, src/machine/system_calls.rs
=> ADDED: delete_file/1, addressing a remaining aspect of #511

src/clause_types.rs, src/lib/files.pl, src/machine/system_calls.rs
This addresses a remaining aspect of #511.
=> ADDED: path_canonical/2, obtaining the canonical absolute path.

README.md
=> DOC: add more links to libraries, and include iso_ext in the enumeration

src/lib/csv.pl
- add `write_csv` predicate
- change  `skip_header` option to `with_header` and fix pb with headerless files
=> add write_csv & change skip_header to with_header option

src/clause_types.rs, src/lib/files.pl, src/machine/system_calls.rs
The code can be simplified once if- and while-let-chains are available:
https://github.com/rust-lang/rust/issues/53667
=> ADDED: file_creation_time/2 and file_access_time/2.

src/lib/format.pl
Example:
?- phrase(format_("~w~w", [_,_]), Ls).
%@    Ls = "AB"
%@ ;  false.
=> FIXED: format_//2: Keep different variables distinct.

README.md
This adds a few recommendations for writing, running and debugging Prolog code to the README.
=> DOC: Development environment recommendations.

Cargo.lock, Cargo.toml, src/machine/mod.rs, src/read.rs
=> Replace dirs with dirs-next

Cargo.lock, Cargo.toml, crates/prolog_parser/Cargo.toml, crates/prolog_parser/src/ast.rs, crates/prolog_parser/src/lexer.rs, crates/prolog_parser/src/lib.rs, crates/prolog_parser/src/macros.rs, crates/prolog_parser/src/parser.rs, crates/prolog_parser/src/put_back_n.rs, crates/prolog_parser/src/tabled_rc.rs
A clone of #774 for the rebis branches
=> Add prolog_parser

src/lib/clpz.pl
This change can be reverted once the issue is resolved.
=> preliminary workaround for #788

src/lib/clpz.pl
These changes are now possible since the underlying issues are correctly resolved in the `rebis-dev` branch.
Thank you a lot!
=> CLP(ℤ) enhancements for Rebis

src/lib/http/http_server.pl
As always, the solution to a problem can be done by adding more layers of abstraction. In this case, I've added the http_route/3 predicate which is a meta_predicate. Handlers created using this predicate can be passed to http_listen without any problem just as before. The rest of the code is working as intended
=> Fix HTTP server on Rebis. Breaking change

README.md
Please review, and merge if applicable. 
Thank you a lot for implementing this flag!
=> explain the new occurs_check flag

src/lib/clpb.pl, src/lib/clpz.pl
Found thanks to 7ea9706c94d054d5ba45585bc9775f65010ca159.
=> Remove duplicated definitions

src/lib/format.pl, src/loader.pl
Also apply it to the generated code in `loader.pl`.
=> Better indentation for nested ( If -> Then ; Else ) constructs

src/lib/format.pl
Nested disjunctions are now better indented.
=> Improvements for library(format)

Dockerfile
New and improved Dockerfile that should be much more resilient against any future major codebase changes. 👍
=> Switched to cargo-chef for preparing the Docker image

src/lib/clpz.pl
=> remove rectractall/1 (built-in since 8188e3d0cfde3f2277232a5e9ff2931873211af6).

README.md
I suggest to add this to the README to make discussions easier to find.
Please merge if you consider this a good idea. Thank you a lot!
=> add a new section about support and discussions

src/lib/builtins.pl
P.S. Also fixes the mix of tabs and spaces in the file.
=> Fix abolish/1 to succeed on non-existing predicates as per standard

src/lib/clpz.pl
Many thanks to @dcnorris for reporting this issue!
=> FIXED: module qualification for between/3 in goal expansion (#941)

Dockerfile
Was experiencing cache issues before that, either due to the image, or due to Docker cache being weird...
=> Dockerfile update: Switched from using @LukeMathWalker's image to using the official Rust image.

Dockerfile
This seems to have really fixed the cache issues for real this time 😅
=> Made rust version in Dockerfile static

src/lib/clpz.pl
Many thanks to @notoria for producing a very short test case.
=> FIXED: correct propagation of tuples_in/2 (#929)

src/lib/builtins.pl
All error checking tests pass with this fix. But there are other test failures not addressed with this pull request.
=> Fix current_predicate/1 predicate error checking

src/lib/clpz.pl
Used in package precautionary by @dcnorris.
=> ENHANCED: Goal expansion for reified constraints.

src/lib/clpz.pl
Example:
?- X #= popcount(3+5).
X = 1.
This builds on #986 provided by @Regan-Koopmans. Many thanks!
=> ADDED: popcount(+Integer)

src/lib/clpz.pl
Many thanks to @notoria and @flexoron for very useful test cases!
=> address #995: wrong results for popcount/1

src/toplevel.pl
Closes https://github.com/mthom/scryer-prolog/issues/1022
=> Add a -f switch to load alternative initialization files

src/lib/iso_ext.pl
=> FIXED: meta_predicate/1 directive for call_nth/2.

src/lib/atts.pl, src/lib/error.pl
Bug: https://github.com/mthom/scryer-prolog/issues/1031
ISO: http://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#C1
=> Fix uninstantiation_error missing. Fix #1031

src/lib/error.pl
This also (partially) addresses #1108.
=> Use '$skip_max_list'/4 for fast list tests in can_be/2 and must_be/2

crates/prolog_parser/src/lexer.rs
This is handy for writing large integers, for example in cryptographic
applications.
This addresses #994.
Examples:
?- X = 1_000_000.
%@    X = 1000000.
?- X = 1_
000_
000.
%@    X = 1000000.
=> ENHANCED: Support '_' followed by layout text sequence in integers.

src/loader.pl
=> ENHANCED: indicate failed initialization/1 goal

src/lib/builtins.pl
=> Correct retract/1 issues due to module qualification

src/lib/serialization/abnf.pl
Those pesky carriage line return feeds. 🙈
=> Fix typo in abnf_lwsp/2

src/machine/machine_state.rs
This is in response to issue #1121.
=> Correct order of variables in read_term/3 equation and variable lists

crates/instructions-template/src/lib.rs, src/lib/sockets.pl, src/machine/system_calls.rs
Related https://github.com/mthom/scryer-prolog/issues/1177
=> fix socket_client_open/3

README.md
This is a small documentation improvement.
=> deterministic --> semi-deterministic

crates/instructions-template/src/lib.rs
=> correct reference to '$working_directory'/2

src/loader.pl
=> ENHANCED: more specific warning when initialization/1 fails (#1149)

src/toplevel.pl
=> ENHANCED: Make toplevel output a Prolog term that can be read back also for "...".

src/forms.rs, src/lib/builtins.pl, src/lib/charsio.pl, src/lib/error.pl, src/lib/lists.pl, src/lib/ordsets.pl, src/machine/machine_errors.rs, src/machine/machine_state_impl.rs, src/machine/partial_string.rs, src/machine/system_calls.rs
This PR answers issues #110, #1023 and #1250 by incorporating Ulrich's improvements to `length/2` along with Ulrich's and Markus' suggested improvements to `'$skip_max_list'/4`.
=> Improved length/2 and arg/3 range checking

src/lib/sgml.pl, src/machine/system_calls.rs
=> FIXED: library(sgml): load_html/3 and load_xml/3 now both work again.

README.md
This applies the same change to `master`.
=> DOC: Better explanation of strings and partial strings.

README.md, src/lib/simplex.pl
=> ADDED: library(simplex), for solving linear programming problems.

.github/workflows/test.yml, Cargo.toml
Reverts mthom/scryer-prolog#1347
=> Revert "Set minimum rust version in Cargo.toml"

build/main.rs
Add an explination when `rustfmt` cannot be found at build time.
=> Improve rustfmt missing error during build (#1379)

src/lib/iso_ext.pl
I hope that this will allow more extensive tests of Scryer Prolog. Enjoy!
=> ENHANCED: more memory efficient call_nth/2 (#1264)

tests/scryer/issues.rs
FIx up some tests after indentation changed for false.
=> Fix indentation before false in tests (#676)

src/machine/system_calls.rs
Small cosmetic fix. Closes #1407
=> Fix reported source for set_output/1 error (#1407)

src/lib/clpz.pl
This adds `sign/1` to `library(clpz)`, addressing https://github.com/triska/clpz/issues/17.
=> ADDED: sign/1

README.md, src/lib/time.pl, src/toplevel.pl
This makes counting solutions easy.
=> ENHANCED: "f" on toplevel to report answers up to the next multiple of 5.

Cargo.lock, Cargo.toml, README.md, scryer-prolog.wxs, src/bin/scryer-prolog.rs
It fixes the build on Windows 10 and adds a very basic MSI installer:
=> Fix build on Windows 10

src/lib/builtins.pl, src/lib/error.pl
This addresses one aspect of #1472.
=> Implement and use can_be(in_character, ...)

src/lib/files.pl, src/lib/pio.pl, src/lib/xpath.pl
Here are several smaller DCG-related improvements to `library(files)` and `library(xpath)`, and an added `meta_predicate` directive to `library(pio)`.
=> Several smaller improvements

src/lib/dcgs.pl
Example:
?- phrase(..., "hello").
true.
This addresses #1577.
=> ENHANCED: Improve determinism of ... //0 and seq//1.

src/lib/si.pl
Examples:
?- chars_si("hello").
true.
?- chars_si(5).
false.
?- chars_si([a,b,c|Rs]).
error(instantiation_error,sort/2).
=> ADDED: chars_si/1, testing for a string

src/lib/crypto.pl
These entailed constraints only affect performance, and can be removed without affecting the correctness of the code. They speed up scalar multiplication of a curve point, used for example in Bitcoinolog.
=> ENHANCED: library(crypto): Faster conversion to bytes when the integer is known

.github/workflows/test.yml
Add a CI step similar to Ubuntu/MacOS
=> Add Windows CI

README.md, src/lib/http/http_server.pl
=> HTTP Server minor fixes

src/lib/clpz.pl
The constraints from `library(clpz)` were already correctly removed, but others such as pending `freeze/2` goals were not, potentially leading to an accumulation of redundant constraints during propagation.
Test case:
?- freeze(A,(X=1;X=2)), all_distinct([A]), A = 1.
A = 1, X = 1
;  A = 1, X = 2.
The combination of `freeze/2` and CLP(ℤ) is useful for example when creating animations of search processes.
This addresses #1624.
=> FIXED: CLP(ℤ): Correctly remove all attributes during propagation of all_distinct/1 and other global constraints.

src/machine/system_calls.rs
=> more uses of newly available deref_register(n)

src/lib/arithmetic.pl
Please, merge if you think it's worth adding to Scryer
=> Add predicate lcm/2 to library(arithmetic)

build/instructions_template.rs, src/lib/builtins.pl, src/machine/dispatch.rs, src/machine/system_calls.rs
I've created this as a branch for others to review and approve before merging.
=> Fix mishandled if-then-else interpretation (#1659)

src/lib/iso_ext.pl
Maybe some predicates could have more information, but I wasn't 100% sure. They can be improved later in any case
=> Compatible Doclog docs for library(iso_ext)

src/lib/clpz.pl
Example:
?- 0 #==> X #= 1/2.
%@    clpz:(X in inf..sup)
%@ ;  false.
This addresses #1501.
=> FIXED: correctly reify (/)/2.

src/lib/charsio.pl
Added documentation to `library(charsio)` predicates
=> Compatible Doclog docs for library(charsio)

INDEX.md
This new file: `INDEX.md` contains the content of the front page at https://www.scryer.pl in Djot format.
=> Add website frontpage

src/lib/dcgs.pl, src/lib/dif.pl
Added docs for `library(dcgs)` and fix `library(dif)`
=> Compatible Doclog docs for library(dcgs)

src/lib/clpz.pl
This is for the upcoming Scryer Prolog website.
=> DOC: improve CLP(ℤ) DocLog documentation

INDEX.md, src/lib/arithmetic.pl
Add documentation for `library(arithmetic)` and fix some typos on INDEX.md
=> Compatible Doclog docs for library(arithmetic) and small fixes on INDEX.md

src/lib/clpz.pl
This addresses #1720, and improves the documentation.
=> CLP(ℤ) corrections

INDEX.md, src/lib/builtins.pl
=> Minor fixes to docs

README.md
Many thanks to @aarroyoc for the documentation system, and for hosting the page!
=> add link to newly available homepage

src/lib/clpz.pl
This is motivated by https://github.com/mthom/scryer-prolog/issues/384#issuecomment-902709060 .
=> DOC: Describe how to use "p" and "w" on the toplevel to write terms without depth limit.

src/lib/error.pl
=> ENHANCED: must_be/2: prefer type error over instantiation error

src/lib/dif.pl
=> ENHANCED: more compact definition of dif/2

src/machine/system_calls.rs
There may be a more elegant way to solve this.
=> FIXED: number_chars(N, "0' "), addressing #1580.

src/lib/clpz.pl
Notably, this addresses the issue discussed in https://github.com/SWI-Prolog/swipl-devel/issues/1160.
=> Various improvements to tuples_in/2

src/lib/clpb.pl
=> remove residual goal for ground BDD

src/heap_print.rs
=> extend logic to all control and whitespace characters

src/lib/gensym.pl
=> gensym-related improvement and correction

src/lib/clpz.pl
=> Small fixes for `CLP(ℤ)`

src/toplevel.pl
=> bracket all operators that are direct operands of (=)/2

README.md
This addresses an important aspect of #1777.
=> advertise newly achieved strong syntactic conformance: all current tests pass

README.md, src/parser/lexer.rs, src/parser/parser.rs, src/read.rs, src/toplevel.pl
This addresses an important aspect of #1777.
=> DOC: new section on applications of Scryer Prolog

build/instructions_template.rs, src/codegen.rs, src/lib/lists.pl, src/machine/dispatch.rs, src/machine/machine_state.rs, src/machine/mod.rs, src/machine/system_calls.rs, src/targets.rs
Example:
?- member(X, "abc").
%@    X = a
%@ ;  X = b
%@ ;  X = c.
This addresses #750.
=> ENHANCED: improved determinism of member/2

src/toplevel.pl
Examples, previously:
$ scryer-prolog -g "member(X,Ls"
?-
$ scryer-prolog -g "member(X,Ls)"
member(_542,_543) causes: error(existence_error(procedure,member/2),member/2)
?-
Now:
$ scryer-prolog -g "member(X,Ls"
"member(X,Ls" cannot be read: error(syntax_error(incomplete_reduction),read_term_from_chars/3:0)
$ scryer-prolog -g "member(X,Ls)"
member(X,Ls) causes: error(existence_error(procedure,member/2),member/2)
?-
This also addresses https://github.com/mthom/scryer-prolog/issues/1185.
=> ENHANCED: use newly available read_term_from_chars/3 for better errors

Cargo.lock, Cargo.toml, src/arena.rs, src/arithmetic.rs, src/forms.rs, src/heap_print.rs, src/machine/arithmetic_ops.rs, src/machine/disjuncts.rs, src/machine/dispatch.rs, src/machine/heap.rs, src/machine/loader.rs, src/machine/machine_state.rs, src/machine/machine_state_impl.rs, src/machine/mod.rs, src/machine/system_calls.rs, src/parser/ast.rs, src/parser/lexer.rs, src/parser/mod.rs, src/parser/parser.rs
This gets rid of the msys2 dependency on windows with a pure rust implementation of big numbers.
Package updated to make this possible currently forked:
https://github.com/coasys/dashu
https://github.com/coasys/libffi-rs
=> Replace rug with dashu

src/lib/clpz.pl
Example:
?- A#=A//A#==>B,A-B=1-1.
A = 1, B = 1.
This addresses #1941.
=> FIXED: do not attach constraint if the propagator is already entailed and killed

src/lib/si.pl
=> add character_si/1 and use it to correct chars_si/1

src/lib/si.pl
Source:
https://github.com/mthom/scryer-prolog/issues/1947#issuecomment-1665113488
=> ENHANCED: more efficient chars_si/1, using specialized predicates of Scryer

src/lib/iso_ext.pl
Specification:
https://www.complang.tuwien.ac.at/ulrich/iso-prolog/prologue#succ
=> ADDED: succ/2, part of the Prologue for Prolog

Cargo.lock, Cargo.toml, src/arena.rs, src/bin/scryer-prolog.rs, src/lib.rs, src/machine/dispatch.rs, src/machine/machine_errors.rs, src/machine/mock_wam.rs, src/machine/mod.rs, src/machine/streams.rs, src/machine/system_calls.rs, src/read.rs
Additional code changes for the upcoming wasm32 support (see #615).
=> Allow users to disable optional features

.github/workflows/ci.yml, src/types.rs
Adds CI to 32-bit builds on Linux.
=> 32 bit CI for Linux

src/lib/iso_ext.pl
=> Corrections to countall/2

.github/workflows/ci.yml
=> Add wasm build steps

Cargo.lock, Cargo.toml, src/arithmetic.rs, src/heap_print.rs, src/machine/arithmetic_ops.rs, src/machine/loader.rs, src/machine/machine_state_impl.rs, src/machine/preprocessor.rs
This PR should fix https://github.com/cmpute/dashu/issues/33. I also made several improvements on the code to make the usage of `dashu` more idomatic. Besides the floored division of big integers is also implemented.
=> Upgrade dashu and make the related code more idomatic.

src/parser/macros.rs
At least it solves my CRLF problem :)
=> Solves CRLF/CR issue by considering'\r' a `layout_char` #553 #2028

src/lib/http/http_server.pl
A more compliant version of url_decode
=> Improved version of url_decode

src/lib/clpz.pl
=> Use the same queue for variables in reified constraints

src/lib/clpz.pl
This addresses all remaining cases from #2083, excepting (//)/2:
?- #\ 1#=(X*X)/0.
clpz:(X in inf..sup).
?- #\ 1#=(X+X)/0.
clpz:(X in inf..sup).
Still remaining:
?- #\ 0#=(Y// -1)/0.
clpz:(-1*Y#=_A).
=> ENHANCED: Remove no longer needed morphed propagators.

src/lib/clpz.pl
Example:
?- B #<==> (0^Y/0) #= Z.
B = 0, clpz:(Y in 0..sup), clpz:(Z in inf..sup).
=> ENHANCED: Omit projection of morphed (^)/2 in disentailed constraints.

src/lib/clpz.pl
=> Queue morphed propagators to give them a chance for propagation

src/machine/machine_state_impl.rs
https://github.com/mthom/scryer-prolog/issues/2214
=> Throw ValidType::Atom error in functor

README.md
This addresses recent questions such as https://github.com/mthom/scryer-prolog/discussions/1909#discussioncomment-7912668.
=> explain starting Scryer Prolog

src/toplevel.pl
From what I tested this doesn't regress #2217.
Closes #2241.
=> Fix anonymous attributed variables not showing in toplevel

src/lib/clpz.pl
This allows subsequently invoked constraints to take the entire filtering results into account, instead of being invoked when the obtained information is not yet entirely used.
The SICStus-style attributed variables mechanism of Scryer Prolog automatically prevents very subtle interaction problems that can arise in systems that do not give all variables that are involved in a unification an opportunity to schedule their propagators.
An example of such a subtle interaction is:
?- tuples_in([[A,C,B]], [[3,1,3],[4,2,4]]),
global_cardinality([A,B,D], [3-1,4-2]),
A = 4.
A = 4 causes pgcc_check/1 and pgcc/2 to be queued in the fast and slow queue, respectively. In the fast queue, there is also rel_tuple/2, which is worked off after gcc_check/1 and simultaneously instantiates both C and B (to 2 …
=> ENHANCED: Suspend propagation during filtering in global_cardinality/2.

Cargo.toml, src/machine/system_calls.rs
https://github.com/mthom/scryer-prolog/issues/2267
=> Use reqwest async and use futures::executor

src/lib/dcgs.pl
=> Prevent assertion of clauses for (-->)/2 when DCGs are enabled.

src/lib/os.pl, tests/scryer/cli/issues/os_argv-no-final--.stdin, tests/scryer/cli/issues/os_argv-no-final--.stdout, tests/scryer/cli/issues/os_argv-no-final--.toml, tests/scryer/cli/issues/os_argv.stdin, tests/scryer/cli/issues/os_argv.stdout, tests/scryer/cli/issues/os_argv.toml
See https://github.com/mthom/scryer-prolog/pull/2263#issuecomment-1874400820
@aarroyoc
=> Fix os:argv/1 in case the raw args contain multiple `--`

src/lib/atts.pl
https://github.com/mthom/scryer-prolog/issues/2298
=> Throw error in call_residue_vars/2

src/lib/iso_ext.pl, src/machine/project_attributes.pl, src/toplevel.pl
https://github.com/mthom/scryer-prolog/issues/2031
=> Move copy_term/3 to library(iso_ext)

src/lib/clpb.pl, src/lib/dcgs.pl
=> No longer use (->)//2 in library(clpb)

src/lib/charsio.pl
Suggested by @librarianmage, many thanks!
=> ENHANCED: Bi-directional char_code/2, addressing #2321.

README.md
Many thanks to @dcnorris for this great application and cooperation!
=> link to newly available paper on analysis of dose-escalation protocols

.github/workflows/ci.yml
=> Install version of iai-callgrind set in Cargo.toml

src/lib/crypto.pl
Without this provision, the expected HMAC can be gathered from timing differences depending on the position where the strings first diverge, and hence an attacker can forge an authenticated message by supplying the gathered HMAC.
Test case, using exp(E) to succeed exactly 2^E times:
exp(E) :-
N is 2^E,
between(1, N, _).
yielding:
?- Options = [algorithm(sha512),hmac([1,2,3])],
Ds = "test",
crypto_data_hash(Ds, H, Options),
phrase((seq(As),seq(Bs)), H),
same_length(Bs, Cs),
maplist(=(a), Cs),
append(As, Cs, H1),
time((exp(10),crypto_data_hash(Ds, H1, Options),false)).
%@    % CPU time: 0.710s, 7_942_187 inferences
%@    % CPU time: 0.713s, 7_942_187 inferences
%@    % CPU time: 0.712s, 7_942_187 inferences
%@    % CPU time: 0.711s, 7_942_187 inferences
%@    % CPU time: 0.710s, 7_942_187 …
=> ENHANCED: Safe HMAC verification, using constant time string comparison.

src/lib/dcgs.pl
=> ADDED: meta_predicate/1 declarations for (',')//2 and (;)//2

src/machine/machine_indices.rs, src/machine/unify.rs
Mentioned here:
- https://github.com/mthom/scryer-prolog/discussions/2409
- https://github.com/aarroyoc/scryer-playground/issues/27
=> Fix warnings of dead code

src/ffi.rs
https://github.com/mthom/scryer-prolog/issues/2416
=> Manage Float and Double FFI types in structs

README.md
We have uploaded a preprint of the paper to arXiv: https://arxiv.org/abs/2406.15293
=> link to newly available paper about Grants4Companies

README.md
=> update Docker install instructions

src/lib/builtins.pl
=> "bound to an atom"

src/lib/tabling.pl
=> s/performance characters/performance characteristics/

benches/run_iai.rs, benches/setup.rs
=> rebis-dev: Fix imports for benches

src/machine/system_calls.rs
Fixes leftover Clippy warnings.
=> Fix clippy warnings

src/lib/format.pl
This addresses #2771.
Many thanks to @tmerr, @UWN, @notoria and @adri326 for your contributions!
=> Correct handling of floats in format/2 and portray_clause/1

src/lib/error.pl
See https://github.com/mthom/scryer-prolog/discussions/2839 for more information.
=> ADDED: call_with_error_context/2

README.md
The WebAssembly example in the README was outdated and no longer matched the current implementation.  
This PR updates the example.
Closes #2870
=> update of the WebAssembly example in README

src/lib/pio.pl
rebis-dev makes the speed difference especially apparent due to the linear scan of strings on the heap in partial_string_tail/2 which is now avoided for repositionable streams, notably files.
This addresses #2888 reported and analyzed by @haijinSk. Many thanks!
=> ENHANCED: dedicated faster branches for repositionable streams

src/lib/builtins.pl
Noted by Oleg Finkelstein. Many thanks!
=> FIXED: invoke correct predicate

.github/workflows/ci.yml, build/instructions_template.rs, build/static_string_indexing.rs, src/atom_table.rs, src/debray_allocator.rs, src/ffi.rs, src/forms.rs, src/functor_macro.rs, src/heap_print.rs, src/iterators.rs, src/machine/compile.rs, src/machine/cycle_detection.rs, src/machine/dispatch.rs, src/machine/heap.rs, src/machine/load_state.rs, src/machine/loader.rs, src/machine/machine_indices.rs, src/machine/machine_state.rs, src/machine/machine_state_impl.rs, src/machine/mock_wam.rs, src/machine/streams.rs, src/machine/system_calls.rs, src/machine/unify.rs, src/parser/ast.rs, src/parser/lexer.rs, src/parser/parser.rs
So that I can rebase my PRs (#2786 and #3009) onto a CI green base,
so that they can be CI green without mixing these chore commits with the functional changes.
=> fix clippy

README.md
An update of the site has caused a change in the address.
=> adapt link to Scryer Prolog Meetup 2024

README.md
Thank you a lot @Skgland for this extremely valuable contribution!
=> add newly available library(process) to the list of libraries
